const test=require("node:test");const assert=require("node:assert/strict");const BloodService=require("../blood-service");
function state(){return BloodService.normalizeBloodState({})}const center={role:"commission",name:"血液中心审核员",orgCode:"BLOOD-DL"};const hospital={role:"institution",name:"医院输血科",username:"hospital",orgCode:"MR1"};
test("dashboard scopes hospital requests to its institution",()=>{const data=state();data.transfusionRequests.push({...data.transfusionRequests[0],id:"BT-OTHER",institutionCode:"MR9"});assert.equal(BloodService.buildDashboard(data,hospital).transfusionRequests.length,1);assert.equal(BloodService.buildDashboard(data,center).transfusionRequests.length,2);});
test("blocked transition is audited and successful release is persisted",()=>{const data=state();const blocked=BloodService.transitionBloodUnit(data,center,"bu-00182","released",{});assert.equal(blocked.status,409);assert.equal(data.bloodAuditEvents[0].action,"transition_blocked");const released=BloodService.transitionBloodUnit(data,center,"bu-00182","released",{testReportSigned:true,dualReview:true});assert.equal(released.status,200);assert.equal(data.bloodUnits[0].status,"released");});
test("clinical request requires assessment and consent",()=>{const data=state();const payload={patientId:"ZY1",bloodType:"O Rh+",component:"悬浮红细胞",amount:"2U",indication:"重度贫血"};assert.equal(BloodService.createRequest(data,hospital,payload).status,409);const result=BloodService.createRequest(data,hospital,{...payload,preAssessmentComplete:true,consentSigned:true});assert.equal(result.status,201);assert.equal(result.body.exchange.type,"blood_order");});
test("trace enforces institution scope",()=>{const data=state();data.bloodUnits[0].hospitalCode="MR2";assert.equal(BloodService.trace(data,hospital,"CN2102-20260711-00182").status,403);assert.equal(BloodService.trace(data,center,"CN2102-20260711-00182").status,200);});
test("specimen identity mismatch is rejected and audited",()=>{const data=state();const result=BloodService.assessSpecimen(data,hospital,{requestId:"BT-0711-0032",patientId:"ZY1",specimenCode:"SP-1",collectorId:"N1",collectedAt:new Date().toISOString(),identityMatched:false,labelComplete:true,hemolysis:false});assert.equal(result.status,422);assert.equal(result.body.specimen.status,"rejected");assert.equal(data.bloodAuditEvents[0].action,"specimen_rejected");});
test("recall changes blood status and emits standard exchange message",()=>{const data=state();data.bloodUnits[0].hospitalCode="MR1";const result=BloodService.createRecall(data,center,{bloodUnitIds:["bu-00182"],reason:"检测报告收回",sourceReportId:"LAB-1"});assert.equal(result.status,201);assert.equal(data.bloodUnits[0].status,"recalled");assert.deepEqual(result.body.recall.affectedInstitutions,["MR1"]);assert.equal(result.body.exchange.type,"recall_notice");});
test("reaction report and emergency allocation enforce business ownership",()=>{const data=state();const reaction=BloodService.reportReaction(data,hospital,{requestId:"BT-0711-0032",severity:"严重",symptoms:["寒战","低血压"],bloodUnitIds:["bu-00182"],immediateActions:["停止输血"]});assert.equal(reaction.status,201);assert.equal(reaction.body.reaction.status,"reported");const allocation=BloodService.createEmergencyAllocation(data,hospital,{bloodType:"O Rh+",component:"悬浮红细胞",amount:"10U",reason:"批量伤员"});assert.equal(allocation.status,201);assert.equal(allocation.body.allocation.status,"requested");});
