const { readRuntimeSource } = require("../src/http/runtime-source");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");
const accessPolicy = require("../access-control-policy");

const {
  STANDARD_TOTALS,
  buildPublicHealthExchangeExceptionBoard,
  buildPublicHealthReadinessReport,
  buildPublicHealthStandardImplementationBoard,
  buildPublicHealthSystem,
  renderMarkdown,
  seedPublicHealthStandardImplementationLedger,
  seedPublicHealthStandards
} = require("../scripts/public-health-readiness");

const ROOT = path.resolve(__dirname, "..");

function readJson(relativePath) {
  return JSON.parse(fs.readFileSync(path.join(ROOT, relativePath), "utf8"));
}

test("public health system covers the full 21/125/421 standard matrix", () => {
  const data = readJson("data/db.json");
  const system = buildPublicHealthSystem({ data });

  assert.equal(system.ok, true);
  assert.deepEqual(system.standardCoverage, STANDARD_TOTALS);
  assert.equal(system.standardDomains.length, 21);
  assert.equal(system.standardCoverage.management.domains, 18);
  assert.equal(system.standardCoverage.management.secondary, 105);
  assert.equal(system.standardCoverage.management.tertiary, 365);
  assert.equal(system.standardCoverage.technology.domains, 3);
  assert.equal(system.standardCoverage.technology.secondary, 20);
  assert.equal(system.standardCoverage.technology.tertiary, 56);
  assert.equal(seedPublicHealthStandards().reduce((sum, item) => sum + item.tertiaryCount, 0), 421);
  assert.equal(system.standardDomains.some((item) => item.name === "传染病防控" && item.tertiaryCount === 49), true);
  assert.equal(system.standardDomains.some((item) => item.name === "网络安全管理" && item.tertiaryCount === 34), true);
  assert.equal(system.standardImplementationLedger.length, 21);
  assert.equal(system.standardImplementationBoard.traceabilityReady, true);
  assert.equal(system.standardImplementationBoard.summary.domains, 21);
  assert.equal(system.standardImplementationBoard.summary.mappingComplete, 21);
  assert.equal(system.standardImplementationBoard.status, "mapping-review-pending");
  assert.equal(system.standardImplementationEvidenceCandidates.length, 0);
  assert.equal(system.summary.standardImplementationAssignedGaps, 0);
  assert.equal(system.summary.standardImplementationVerifiedGaps, 0);
  assert.equal(system.summary.standardImplementationUnassignedGaps, 0);
  assert.equal(system.summary.standardImplementationDueSoonGaps, 0);
  assert.equal(system.summary.standardImplementationOverdueGaps, 0);
  assert.equal(system.cutoverReadiness.readinessLevel, "blocked");
  assert.equal(system.cutoverReadiness.releaseGate, "site-evidence-required");
  assert.equal(system.cutoverDrills.length >= 4, true);
  assert.equal(system.cutoverDrillBoard.status, "blocked");
  assert.equal(system.cutoverDrillBoard.summary.openFindings >= 4, true);
  assert.equal(system.productionHandoffs.length >= 6, true);
  assert.equal(system.productionHandoffBoard.status, "blocked");
  assert.equal(system.productionHandoffBoard.summary.blockedHandoffs >= 6, true);
});

test("standard implementation remediation watch separates unassigned due-soon overdue and verified rows", () => {
  const ledger = seedPublicHealthStandardImplementationLedger().map((item) => {
    if (item.id === "phsil-infectious") return { ...item, status: "escalated", gapStatus: "assigned", remediationStatus: "assigned", remediationOwner: "standards owner", remediationDueAt: "2026-07-09" };
    if (item.id === "phsil-parasitic") return { ...item, status: "gap-recorded", gapStatus: "open", remediationStatus: "not-planned" };
    if (item.id === "phsil-immunization") return { ...item, status: "gap-recorded", gapStatus: "assigned", remediationStatus: "assigned", remediationOwner: "immunization owner", remediationDueAt: "2026-07-15" };
    if (item.id === "phsil-chronic") return { ...item, status: "evidence-linked", gapStatus: "verified", remediationStatus: "verified", remediationOwner: "chronic owner", remediationDueAt: "2026-07-01" };
    return item;
  });
  const board = buildPublicHealthStandardImplementationBoard(ledger, seedPublicHealthStandards(), { now: "2026-07-10T09:00:00+08:00" });

  assert.equal(board.status, "remediation-overdue");
  assert.equal(board.summary.gaps, 3);
  assert.equal(board.summary.unassignedRemediations, 1);
  assert.equal(board.summary.dueSoonRemediations, 1);
  assert.equal(board.summary.overdueRemediations, 1);
  assert.equal(board.entries.find((item) => item.id === "phsil-infectious").remediationOverdue, true);
  assert.equal(board.entries.find((item) => item.id === "phsil-immunization").remediationDueInDays, 5);
  assert.equal(board.entries.find((item) => item.id === "phsil-parasitic").remediationUnassigned, true);
  assert.equal(board.entries.find((item) => item.id === "phsil-chronic").remediationOverdue, false);
});

test("exchange exception compensation board separates resolved, assigned, due-soon and overdue failures", () => {
  const board = buildPublicHealthExchangeExceptionBoard([
    { id: "run-replayed", category: "laboratory", failedRecords: 2, compensationStatus: "replayed", receiptStatus: "accepted-after-retry" },
    { id: "run-assigned", category: "maternal-child", failedRecords: 1, exceptionStatus: "assigned", exceptionOwner: "妇幼接口负责人", exceptionDueAt: "2026-07-15" },
    { id: "run-overdue", category: "direct-report", failedRecords: 1, exceptionStatus: "escalated", exceptionOwner: "疾控直报负责人", exceptionDueAt: "2026-07-09" },
    { id: "run-open", category: "security", failedRecords: 1, compensationStatus: "manual-review" }
  ], { now: "2026-07-10T09:00:00+08:00" });

  assert.equal(board.status, "exchange-exception-overdue");
  assert.equal(board.summary.exceptions, 4);
  assert.equal(board.summary.openExceptions, 3);
  assert.equal(board.summary.resolvedExceptions, 1);
  assert.equal(board.summary.unassignedExceptions, 1);
  assert.equal(board.summary.dueSoonExceptions, 1);
  assert.equal(board.summary.overdueExceptions, 1);
  assert.equal(board.entries.find((item) => item.id === "run-replayed").exceptionOpen, false);
  assert.equal(board.entries.find((item) => item.id === "run-assigned").exceptionDueInDays, 5);
  assert.equal(board.entries.find((item) => item.id === "run-overdue").exceptionOverdue, true);
});

test("public health readiness exposes institution scopes, event loop, and exchange tasks", () => {
  const data = readJson("data/db.json");
  const report = buildPublicHealthReadinessReport({ data });

  assert.equal(report.ok, true);
  assert.equal(report.institutionScopes.length >= 7, true);
  assert.equal(report.institutionScopes.some((item) => /疾病预防控制中心/.test(item.name)), true);
  assert.equal(report.institutionScopes.some((item) => /二级及以上医院/.test(item.name)), true);
  assert.equal(report.institutionScopes.some((item) => /卫生健康监督机构/.test(item.name)), true);
  assert.equal(report.riskQueue.length >= 3, true);
  assert.equal(report.riskQueue.every((item) => item.commandAction && item.followupAction && item.linkedStandardItems.length), true);
  ["direct-report", "laboratory", "immunization", "maternal-child", "emergency", "security"].forEach((category) => {
    assert.equal(report.exchangeTasks.some((item) => item.category === category), true, `${category} exchange task missing`);
  });
  assert.equal(report.exchangeRuns.length >= 6, true);
  assert.equal(report.exchangeRuns.every((item) => item.receiptStatus && item.compensationStatus), true);
  assert.equal(report.exchangeRuns.some((item) => item.compensationStatus === "replayed" || item.compensationStatus === "manual-review"), true);
  assert.equal(report.highlights.summary.capabilities, 5);
  assert.equal(report.highlights.formalGoLiveState, "blocked-until-site-evidence-signed");
  assert.equal(report.exchangeExceptionBoard.summary.exceptions >= 2, true);
  assert.equal(report.exchangeExceptionBoard.summary.openExceptions >= 1, true);
  assert.equal(report.summary.exchangeExceptions, report.exchangeExceptionBoard.summary.exceptions);
  assert.equal(report.summary.openExchangeExceptions, report.exchangeExceptionBoard.summary.openExceptions);
  assert.equal(report.institutionTasks.length >= 7, true);
  assert.equal(report.institutionTasks.every((item) => item.scopeId && item.owner && item.handoffStatus && item.accountStatus), true);
  assert.equal(report.onsiteAcceptances.length >= 6, true);
  assert.equal(report.onsiteAcceptances.every((item) => item.owner && item.blocker && item.onsiteAction), true);
  assert.equal(report.cutoverBlockers.length >= 6, true);
  assert.equal(report.cutoverBlockers.every((item) => item.owner && item.dependency && item.blocker && item.requiredEvidence.length && item.resolutionAction), true);
  assert.equal(report.cutoverBlockers.every((item) => item.assignee && item.remediationStatus && item.siteWindow && item.reminderChannel && item.escalationLevel), true);
  assert.equal(report.openCutoverBlockers.some((item) => item.severity === "P0" && item.linkedAcceptanceId), true);
  assert.equal(report.cutoverReadiness.readinessLevel, "blocked");
  assert.equal(report.cutoverReadiness.releaseGate, "site-evidence-required");
  assert.equal(report.cutoverReadiness.nextActions.length >= report.openCutoverBlockers.length, true);
  assert.equal(report.cutoverReadiness.summary.p0Open >= 1, true);
  assert.equal(report.cutoverEvidencePackets.length >= 6, true);
  assert.equal(report.cutoverEvidencePackets.reduce((sum, item) => sum + item.requiredItems.length, 0) >= 20, true);
  assert.equal(report.cutoverEvidencePackets.every((item) => item.blockerId && item.assignee && item.requiredItems.length), true);
  assert.equal(report.cutoverEvidenceBoard.summary.packets >= 6, true);
  assert.equal(report.cutoverEvidenceBoard.summary.requiredItems >= 20, true);
  assert.equal(report.cutoverEvidenceBoard.summary.missingItems >= 20, true);
  assert.equal(report.siteEvidenceBridge.status, "missing-site-evidence");
  assert.equal(report.siteEvidenceBridge.summary.links >= 8, true);
  assert.equal(report.siteEvidenceBridge.summary.linkedItems >= 20, true);
  assert.equal(report.siteEvidenceBridge.summary.missingLinks >= 1, true);
  assert.equal(report.siteEvidenceVerificationTasks.length >= 9, true);
  assert.equal(report.siteEvidenceVerificationTasks.every((item) => item.linkId && item.templateId && item.packetId && item.owner && item.reviewerRole && item.verificationWindow && item.requiredChecks?.length >= 3 && item.escalationPath?.length >= 2), true);
  assert.equal(report.siteEvidenceVerificationBoard.status, "evidence-pending");
  assert.equal(report.siteEvidenceVerificationBoard.summary.tasks >= 9, true);
  assert.equal(report.siteEvidenceVerificationBoard.summary.structurallyReadyTasks, report.siteEvidenceVerificationBoard.summary.tasks);
  assert.equal(report.siteEvidenceVerificationBoard.summary.verifiedTasks, 0);
  assert.equal(report.standardImplementationLedger.length, 21);
  assert.equal(report.standardImplementationBoard.traceabilityReady, true);
  assert.equal(report.standardImplementationBoard.summary.mappingComplete, 21);
  assert.equal(report.standardImplementationBoard.summary.gaps, 0);
  assert.equal(report.standardImplementationBoard.status, "mapping-review-pending");
  assert.equal(report.standardImplementationEvidenceCandidates.length, 0);
  assert.equal(report.summary.standardImplementationAssignedGaps, 0);
  assert.equal(report.summary.standardImplementationVerifiedGaps, 0);
  assert.equal(report.summary.standardImplementationUnassignedGaps, 0);
  assert.equal(report.summary.standardImplementationDueSoonGaps, 0);
  assert.equal(report.summary.standardImplementationOverdueGaps, 0);
  assert.equal(report.launchGate.requirements.some((item) => item.id === "launch-site-evidence-verification" && !item.passed), true);
  assert.equal(report.launchApprovals.length >= 6, true);
  assert.equal(report.launchApprovals.every((item) => item.role && item.owner && item.status), true);
  assert.equal(report.launchGate.releaseGate, "site-evidence-required");
  assert.equal(report.launchGate.productionReady, false);
  assert.equal(report.launchGate.requirements.length >= 8, true);
  assert.equal(report.launchGate.summary.blockedRequirements >= 1, true);
  assert.equal(report.cutoverDrills.length >= 4, true);
  assert.equal(report.cutoverDrillBoard.status, "blocked");
  assert.equal(report.cutoverDrillBoard.summary.drills >= 4, true);
  assert.equal(report.cutoverDrillBoard.summary.linkedBlockers >= 5, true);
  assert.equal(report.cutoverDrillBoard.summary.openFindings >= 4, true);
  assert.equal(report.productionHandoffs.length >= 6, true);
  assert.equal(report.productionHandoffs.every((item) => item.packageType && item.requiredSignoffs?.length && item.releaseArtifacts?.length), true);
  assert.equal(report.productionHandoffBoard.status, "blocked");
  assert.equal(report.productionHandoffBoard.summary.handoffs >= 6, true);
  assert.equal(report.productionHandoffBoard.summary.linkedEvidencePackets >= 5, true);
  assert.equal(report.productionHandoffBoard.summary.releaseArtifacts >= 8, true);
  assert.equal(report.productionHandoffBoard.summary.pendingHandoffs >= 6, true);
  assert.equal(report.productionHandoffBoard.summary.blockedHandoffs >= 6, true);
  assert.equal(report.launchGate.requirements.some((item) => item.id === "launch-production-handoffs" && !item.passed), true);
  assert.equal(report.goLiveObservations.length >= 6, true);
  assert.equal(report.goLiveObservations.every((item) => item.rollbackTrigger && item.rollbackOwner && item.threshold), true);
  assert.equal(report.goLiveObservationBoard.status, "watch-ready");
  assert.equal(report.goLiveObservationBoard.summary.observations >= 6, true);
  assert.equal(report.goLiveObservationBoard.summary.planReady >= 6, true);
  assert.equal(report.goLiveObservationBoard.summary.rollbackPlans >= 6, true);
  assert.equal(report.goLiveObservationBoard.summary.pendingObservations >= 6, true);
  assert.equal(report.goLiveObservationBoard.summary.openCriticalSignals, 0);
  assert.equal(report.launchGate.requirements.some((item) => item.id === "launch-go-live-observation" && item.passed), true);
  assert.equal(report.launchIncidents.length >= 6, true);
  assert.equal(report.launchIncidents.every((item) => item.lane && item.sla && item.rollbackDecisionOwner && item.escalationPath?.length && item.requiredArtifacts?.length), true);
  assert.equal(report.launchIncidentBoard.status, "desk-ready");
  assert.equal(report.launchIncidentBoard.summary.lanes >= 6, true);
  assert.equal(report.launchIncidentBoard.summary.deskReady >= 6, true);
  assert.equal(report.launchIncidentBoard.summary.rollbackDecisionOwners >= 4, true);
  assert.equal(report.launchIncidentBoard.summary.criticalOpenTickets, 0);
  assert.equal(report.launchGate.requirements.some((item) => item.id === "launch-incident-desk" && item.passed), true);
  assert.equal(report.launchDutyShifts.length >= 6, true);
  assert.equal(report.launchDutyShifts.every((item) => item.shiftWindow && item.owner && item.backupOwner && item.contactChannel && item.escalationOwner && item.handoffChecklist?.length && item.requiredArtifacts?.length), true);
  assert.equal(report.launchDutyBoard.status, "roster-ready");
  assert.equal(report.launchDutyBoard.summary.shifts >= 6, true);
  assert.equal(report.launchDutyBoard.summary.readyShifts >= 6, true);
  assert.equal(report.launchDutyBoard.summary.backupContacts >= 6, true);
  assert.equal(report.launchDutyBoard.summary.missedHandoffs, 0);
  assert.equal(report.launchGate.requirements.some((item) => item.id === "launch-duty-handoffs" && item.passed), true);
  assert.equal(report.launchCommandBriefs.length >= 5, true);
  assert.equal(report.launchCommandBriefs.every((item) => item.briefWindow && item.owner && item.recorder && item.publishChannel && item.publishTarget && item.decisionOwner && item.sourceBoards?.length && item.linkedDutyShiftIds?.length && item.linkedObservationIds?.length && item.linkedIncidentIds?.length && item.requiredSections?.length), true);
  assert.equal(report.launchCommandBriefBoard.status, "briefing-ready");
  assert.equal(report.launchCommandBriefBoard.summary.briefs >= 5, true);
  assert.equal(report.launchCommandBriefBoard.summary.readyBriefs >= 5, true);
  assert.equal(report.launchCommandBriefBoard.summary.sourceBoards >= 4, true);
  assert.equal(report.launchCommandBriefBoard.summary.blockedBriefs, 0);
  assert.equal(report.launchCommandBriefBoard.summary.expectedAcknowledgements, 0);
  assert.equal(report.launchCommandBriefBoard.summary.acknowledgedRecipients, 0);
  assert.equal(report.launchCommandBriefBoard.summary.pendingAcknowledgements, 0);
  assert.equal(report.launchGate.requirements.some((item) => item.id === "launch-command-briefs" && item.passed), true);
  assert.equal(report.launchGate.approvalPreflight.status, "blocked");
  assert.equal(report.launchGate.approvalPreflight.blockedPrerequisites >= 1, true);
  assert.equal(report.launchGate.approvalPreflight.blockedRequirementIds.includes("launch-site-evidence-verification"), true);
  ["publicHealth:highlightCapabilities", "api:highlight-actions", "frontend:highlight-center"].forEach((id) => {
    assert.equal(report.checks.some((item) => item.id === id && item.passed), true, `${id} check missing`);
  });
  ["standard:implementation-ledger", "exchange:runs", "exchange:compensation", "institution:tasks", "onsite:acceptance", "cutover:blockers", "cutover:open-boundary", "cutover:evidence-packets", "cutover:readiness-board", "cutover:drill-board", "production:handoffs", "go-live:observation-plan", "go-live:incident-desk", "go-live:duty-handoffs", "go-live:command-briefs", "go-live:command-brief-delivery-receipts", "site-evidence:bridge", "site-evidence:verification-desk", "launch:gate", "launch:approval-preflight", "frontend:standard-implementation-panel", "frontend:standard-implementation-actions", "frontend:cutover-readiness-panel", "frontend:cutover-evidence-panel", "frontend:cutover-drill-panel", "frontend:production-handoff-panel", "frontend:go-live-observation-panel", "frontend:launch-incident-panel", "frontend:launch-duty-panel", "frontend:launch-command-brief-panel", "frontend:launch-command-brief-receipts", "frontend:site-evidence-bridge-panel", "frontend:site-evidence-verification-panel", "frontend:launch-gate-panel", "frontend:launch-approval-preflight", "api:standard-implementation-ledger", "api:cutover-readiness", "api:cutover-evidence-packets", "api:cutover-drills", "api:production-handoffs", "api:go-live-observations", "api:launch-incidents", "api:launch-duty-shifts", "api:launch-command-briefs", "api:site-evidence-bridge", "api:site-evidence-verification-tasks", "api:launch-gate", "docs:production-handoffs", "docs:go-live-observations", "docs:launch-incidents", "docs:launch-duty", "docs:launch-command-briefs"].forEach((id) => {
    assert.equal(report.checks.some((item) => item.id === id && item.passed), true, `${id} check missing`);
  });
  assert.equal(report.checks.every((item) => item.passed), true);

  const markdown = renderMarkdown(report);
  assert.match(markdown, /Public health informatization readiness report/);
  assert.match(markdown, /Standard implementation ledger/);
  assert.match(markdown, /Delivery receipts/);
  assert.match(markdown, /传染病防控/);
  assert.match(markdown, /二级及以上医院/);
  assert.match(markdown, /direct-report/);
  assert.match(markdown, /Exchange runs/);
  assert.match(markdown, /On-site acceptance/);
  assert.match(markdown, /Production cutover readiness/);
  assert.match(markdown, /site-evidence-required/);
  assert.match(markdown, /Production cutover evidence packets/);
  assert.match(markdown, /Production cutover drills/);
  assert.match(markdown, /Production handoff packs/);
  assert.match(markdown, /Go-live observation and rollback watch/);
  assert.match(markdown, /Launch incident triage and rollback decision desk/);
  assert.match(markdown, /Launch duty roster and command handoff desk/);
  assert.match(markdown, /Launch command briefs and status broadcast desk/);
  assert.match(markdown, /Approval preflight: blocked/);
  assert.match(markdown, /Public health site evidence bridge/);
  assert.match(markdown, /Site evidence verification task desk/);
  assert.match(markdown, /Production cutover blockers/);
  assert.match(markdown, /Production launch gate/);
  assert.match(markdown, /Production launch approvals/);
});

test("public health page, API, docs and release manifest are wired", () => {
  const server = readRuntimeSource(ROOT);
  const html = fs.readFileSync(path.join(ROOT, "public-health.html"), "utf8");
  const js = fs.readFileSync(path.join(ROOT, "public-health.js"), "utf8");
  const pkg = readJson("package.json");
  const doc = fs.readFileSync(path.join(ROOT, "docs", "公共卫生信息化系统建设报告.md"), "utf8");
  const plan = fs.readFileSync(path.join(ROOT, "docs", "公共卫生信息化下一步开发计划.md"), "utf8");
  const manifest = fs.readFileSync(path.join(ROOT, "scripts", "release-artifact-manifest.js"), "utf8");

  assert.match(server, /\/api\/public-health\/system/);
  assert.match(server, /\/api\/public-health\/events\/:id\/actions/);
  assert.match(server, /\/api\/public-health\/exchange-tasks\/:id\/runs/);
  assert.match(server, /\/api\/public-health\/exchange-runs\/:id\/actions/);
  assert.match(server, /\/api\/public-health\/institution-tasks\/:id\/actions/);
  assert.match(server, /\/api\/public-health\/onsite-acceptances\/:id\/actions/);
  assert.match(server, /\/api\/public-health\/cutover-blockers\/:id\/actions/);
  assert.match(server, /\/api\/public-health\/cutover-readiness/);
  assert.match(server, /\/api\/public-health\/cutover-evidence-packets/);
  assert.match(server, /\/api\/public-health\/cutover-evidence-packets\/:id\/actions/);
  assert.match(server, /\/api\/public-health\/cutover-drills/);
  assert.match(server, /\/api\/public-health\/cutover-drills\/:id\/actions/);
  assert.match(server, /\/api\/public-health\/production-handoffs/);
  assert.match(server, /\/api\/public-health\/production-handoffs\/:id\/actions/);
  assert.match(server, /\/api\/public-health\/go-live-observations/);
  assert.match(server, /\/api\/public-health\/go-live-observations\/:id\/actions/);
  assert.match(server, /\/api\/public-health\/launch-incidents/);
  assert.match(server, /\/api\/public-health\/launch-incidents\/:id\/actions/);
  assert.match(server, /\/api\/public-health\/launch-duty-shifts/);
  assert.match(server, /\/api\/public-health\/launch-duty-shifts\/:id\/actions/);
  assert.match(server, /\/api\/public-health\/launch-command-briefs/);
  assert.match(server, /\/api\/public-health\/launch-command-briefs\/:id\/actions/);
  assert.match(server, /\/api\/public-health\/site-evidence-bridge/);
  assert.match(server, /\/api\/public-health\/site-evidence-bridge\/actions/);
  assert.match(server, /\/api\/public-health\/site-evidence-verification-tasks/);
  assert.match(server, /\/api\/public-health\/site-evidence-verification-tasks\/:id\/actions/);
  assert.match(server, /\/api\/public-health\/launch-gate/);
  assert.match(server, /\/api\/public-health\/launch-gate\/actions/);
  assert.match(server, /public-health-event-action/);
  assert.match(server, /public-health-exchange-run/);
  assert.match(server, /public-health-exchange-exception-action/);
  assert.match(server, /public-health-institution-task-action/);
  assert.match(server, /public-health-onsite-acceptance/);
  assert.match(server, /public-health-cutover-blocker-action/);
  assert.match(server, /public-health-cutover-readiness/);
  assert.match(server, /public-health-cutover-evidence-packet-action/);
  assert.match(server, /public-health-cutover-drill-action/);
  assert.match(server, /public-health-production-handoff-action/);
  assert.match(server, /public-health-go-live-observation-action/);
  assert.match(server, /public-health-launch-incident-action/);
  assert.match(server, /public-health-launch-duty-shift-action/);
  assert.match(server, /public-health-launch-command-briefs/);
  assert.match(server, /public-health-launch-command-brief-action/);
  assert.match(server, /public-health-site-evidence-bridge-action/);
  assert.match(server, /public-health-site-evidence-verification-action/);
  assert.match(server, /public-health-launch-gate-action/);
  assert.match(server, /buildPublicHealthSystem/);
  assert.match(html, /public-health-metrics/);
  assert.match(html, /public-health-exchange-runs/);
  assert.match(html, /public-health-institution-tasks/);
  assert.match(html, /public-health-onsite-acceptances/);
  assert.match(html, /public-health-cutover-readiness/);
  assert.match(html, /public-health-cutover-evidence-packets/);
  assert.match(html, /public-health-cutover-drills/);
  assert.match(html, /public-health-production-handoffs/);
  assert.match(html, /public-health-go-live-observations/);
  assert.match(html, /public-health-launch-incidents/);
  assert.match(html, /public-health-launch-duty-shifts/);
  assert.match(html, /public-health-launch-command-briefs/);
  assert.match(html, /public-health-cutover-blockers/);
  assert.match(html, /public-health-site-evidence-bridge/);
  assert.match(html, /public-health-site-evidence-verification/);
  assert.match(html, /public-health-launch-gate/);
  assert.match(js, /renderPublicHealthSystem/);
  assert.match(js, /data-public-health-action/);
  assert.match(js, /data-public-health-latest-action/);
  assert.match(js, /data-public-health-exchange-run/);
  assert.match(js, /data-public-health-exchange-exception/);
  assert.match(js, /data-public-health-institution-task/);
  assert.match(js, /data-public-health-onsite-acceptance/);
  assert.match(js, /renderCutoverReadiness/);
  assert.match(js, /buildStaticCutoverReadiness/);
  assert.match(js, /renderCutoverEvidencePackets/);
  assert.match(js, /data-public-health-cutover-evidence-packet/);
  assert.match(js, /renderCutoverDrills/);
  assert.match(js, /data-public-health-cutover-drill/);
  assert.match(js, /buildStaticCutoverDrillBoard/);
  assert.match(js, /renderProductionHandoffs/);
  assert.match(js, /data-public-health-production-handoff/);
  assert.match(js, /buildStaticProductionHandoffBoard/);
  assert.match(js, /renderGoLiveObservations/);
  assert.match(js, /data-public-health-go-live-observation/);
  assert.match(js, /buildStaticGoLiveObservationBoard/);
  assert.match(js, /renderLaunchIncidents/);
  assert.match(js, /data-public-health-launch-incident/);
  assert.match(js, /buildStaticLaunchIncidentBoard/);
  assert.match(js, /renderLaunchDutyShifts/);
  assert.match(js, /data-public-health-launch-duty-shift/);
  assert.match(js, /buildStaticLaunchDutyBoard/);
  assert.match(js, /renderLaunchCommandBriefs/);
  assert.match(js, /data-public-health-launch-command-brief/);
  assert.match(js, /data-public-health-launch-command-brief-receipt-target/);
  assert.match(js, /acknowledge-launch-command-brief/);
  assert.match(js, /escalate-launch-command-brief-receipt/);
  assert.match(js, /buildStaticLaunchCommandBriefBoard/);
  assert.match(js, /data-public-health-cutover-blocker/);
  assert.match(js, /renderSiteEvidenceBridge/);
  assert.match(js, /data-public-health-site-evidence-link/);
  assert.match(js, /buildStaticSiteEvidenceBridge/);
  assert.match(js, /renderSiteEvidenceVerificationTasks/);
  assert.match(js, /data-public-health-site-evidence-verification-task/);
  assert.match(js, /buildStaticSiteEvidenceVerificationBoard/);
  assert.match(js, /renderLaunchGate/);
  assert.match(js, /data-public-health-launch-approval/);
  assert.match(js, /buildStaticLaunchGate/);
  assert.deepEqual([...accessPolicy.pageCatalog["public-health.html"].roles], ["commission"]);
  assert.deepEqual([...accessPolicy.pageCatalog["public-health.html"].capabilities], ["publicHealth"]);
  assert.equal(pkg.scripts["public-health:readiness"], "node scripts/public-health-readiness.js");
  assert.match(doc, /21\/125\/421/);
  assert.match(doc, /平战结合/);
  assert.match(doc, /医防融合/);
  assert.match(doc, /\/api\/public-health\/system/);
  assert.match(doc, /\/api\/public-health\/events\/:id\/actions/);
  assert.match(doc, /\/api\/public-health\/exchange-tasks\/:id\/runs/);
  assert.match(doc, /\/api\/public-health\/exchange-runs\/:id\/actions/);
  assert.match(doc, /assign-exchange-exception/);
  assert.match(doc, /resolve-exchange-exception/);
  assert.match(doc, /publicHealthExchangeRuns/);
  assert.match(doc, /publicHealthInstitutionTasks/);
  assert.match(doc, /publicHealthOnsiteAcceptances/);
  assert.match(doc, /publicHealthCutoverBlockers/);
  assert.match(doc, /\/api\/public-health\/cutover-blockers\/:id\/actions/);
  assert.match(doc, /publicHealthCutoverReadiness/);
  assert.match(doc, /\/api\/public-health\/cutover-readiness/);
  assert.match(doc, /publicHealthCutoverEvidencePackets/);
  assert.match(doc, /\/api\/public-health\/cutover-evidence-packets\/:id\/actions/);
  assert.match(doc, /publicHealthCutoverDrills/);
  assert.match(doc, /\/api\/public-health\/cutover-drills\/:id\/actions/);
  assert.match(doc, /publicHealthProductionHandoffs/);
  assert.match(doc, /\/api\/public-health\/production-handoffs\/:id\/actions/);
  assert.match(doc, /production handoff/);
  assert.match(doc, /publicHealthGoLiveObservations/);
  assert.match(doc, /\/api\/public-health\/go-live-observations\/:id\/actions/);
  assert.match(doc, /go-live observation/);
  assert.match(doc, /publicHealthLaunchIncidents/);
  assert.match(doc, /\/api\/public-health\/launch-incidents\/:id\/actions/);
  assert.match(doc, /launch incident desk/);
  assert.match(doc, /publicHealthLaunchDutyShifts/);
  assert.match(doc, /\/api\/public-health\/launch-duty-shifts\/:id\/actions/);
  assert.match(doc, /launch duty handoff/);
  assert.match(doc, /publicHealthLaunchCommandBriefs/);
  assert.match(doc, /\/api\/public-health\/launch-command-briefs\/:id\/actions/);
  assert.match(doc, /launch command brief/);
  assert.match(doc, /acknowledge-launch-command-brief/);
  assert.match(doc, /delivery receipt/);
  assert.match(doc, /publicHealthSiteEvidenceBridge/);
  assert.match(doc, /\/api\/public-health\/site-evidence-bridge\/actions/);
  assert.match(doc, /publicHealthSiteEvidenceVerificationTasks/);
  assert.match(doc, /\/api\/public-health\/site-evidence-verification-tasks\/:id\/actions/);
  assert.match(doc, /publicHealthLaunchApprovals/);
  assert.match(doc, /\/api\/public-health\/launch-gate\/actions/);
  assert.match(plan, /5 小时开发切片/);
  assert.match(plan, /事件处置闭环/);
  assert.match(plan, /验收清单/);
  assert.match(plan, /publicHealthLaunchCommandBriefs/);
  assert.match(plan, /acknowledge-launch-command-brief/);
  assert.match(manifest, /public-health-readiness-report\.md/);
  assert.match(manifest, /public-health:readiness/);
});
