const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const ROOT = path.resolve(__dirname, "..");

function read(file) {
  return fs.readFileSync(path.join(ROOT, file), "utf8");
}

test("role pages keep explicit page guards", () => {
  const guards = {
    "citizen.html": "citizen",
    "mobile-preview.html": "citizen",
    "institution.html": "institution",
    "insurance.html": "insurance",
    "county.html": "county",
    "index.html": "commission",
    "health-dashboard.html": "commission",
    "platform.html": "commission",
    "workbench.html": "commission",
    "quality-safety.html": "commission"
  };
  Object.entries(guards).forEach(([file, role]) => {
    assert.match(read(file), new RegExp(`requireRole\\(\\[\\"${role}\\"\\]\\)`), `${file} 缺少 ${role} 页面守卫`);
  });
});

test("citizen pages do not expose cross-role module links or management collections", () => {
  const citizenHtml = `${read("citizen.html")}\n${read("mobile-preview.html")}`;
  ["institution.html", "insurance.html", "county.html", "index.html", "platform.html", "workbench.html", "quality-safety.html", "health-dashboard.html"].forEach((target) => {
    assert.doesNotMatch(citizenHtml, new RegExp(`href=[\\"']\\./${target}`), `居民页面不应链接到 ${target}`);
  });

  const citizenAssets = `${citizenHtml}\n${read("citizen.js")}`;
  ["authUsers", "securityEvents", "applicationCatalog", "institutionCreditEvaluations", "securityAcceptanceLedger"].forEach((key) => {
    assert.doesNotMatch(citizenAssets, new RegExp(`\\b${key}\\b`), `居民端资产不应依赖管理集合 ${key}`);
  });
});

test("application pages avoid placeholder navigation", () => {
  const pages = ["about.html", "citizen.html", "mobile-preview.html", "institution.html", "insurance.html", "county.html", "index.html", "platform.html", "workbench.html", "quality-safety.html", "health-dashboard.html"];
  pages.forEach((file) => assert.doesNotMatch(read(file), /href=["']#["']/, `${file} 存在空链接占位`));
});

test("about page documents runnable platform capabilities", () => {
  const about = read("about.html");
  const auth = read("auth.js");
  assert.match(about, /data-about-section="runtime-capabilities"/);
  assert.match(about, /data-about-section="role-portals"/);
  assert.match(about, /data-about-capability="service-acceptance"/);
  assert.match(about, /data-about-capability="site-template-readmes"/);
  assert.match(about, /data-about-capability="workflow-tasks"/);
  assert.match(about, /data-about-capability="chronic-care"/);
  assert.match(about, /data-about-capability="county-consortium"/);
  assert.match(about, /data-about-section="policy-basis"/);
  assert.match(about, /data-policy-id="chronic-care-2025"/);
  assert.match(about, /data-policy-id="tiered-care-2026"/);
  assert.match(about, /data-about-section="multi-practice-policy"/);
  assert.match(about, /docs\/政策依据说明\.md/);
  assert.match(about, /\/api\/multi-practice-registry/);
  assert.match(about, /\/api\/service-acceptance-summary/);
  assert.match(about, /\/api\/site-template-readmes/);
  assert.match(about, /\/api\/tasks/);
  assert.match(about, /npm run deploy:check/);
  assert.match(read("index.html"), /href="\.\/about\.html"/);
  assert.match(read("institution.html"), /href="\.\/about\.html"/);
  assert.match(read("insurance.html"), /href="\.\/about\.html"/);
  assert.match(read("county.html"), /href="\.\/about\.html"/);
  assert.match(read("citizen.html"), /href="\.\/about\.html"/);
  assert.match(read("workbench.html"), /href="\.\/about\.html"/);
  assert.match(read("platform.html"), /href="\.\/about\.html"/);
  assert.match(read("health-city.html"), /href="\.\/about\.html"/);
  assert.match(auth, /\["about\.html", "关于"\]/);
  assert.match(auth, /pageName === "about\.html"/);
  assert.doesNotMatch(about, /requireRole/);
});

test("policy basis document maps policies to runnable platform evidence", () => {
  const doc = read("docs/政策依据说明.md");
  assert.match(doc, /国卫基层发〔2025〕15号/);
  assert.match(doc, /国卫办基层函〔2025〕439号/);
  assert.match(doc, /国办发〔2026〕11号/);
  assert.match(doc, /国卫医发〔2014〕86号/);
  assert.match(doc, /flowchart TD/);
  assert.match(doc, /\/api\/chronic\/risk-stratification/);
  assert.match(doc, /\/api\/multi-practice-registry/);
  assert.match(doc, /npm\.cmd run priority-apps:templates/);
});

test("about page documents doctor multi-practice policy boundaries", () => {
  const about = read("about.html");
  const doc = read("docs/医师多点执业政策说明.md");
  const report = read("docs/医师多点执业主要功能报告.md");
  assert.match(about, /医生账户与多点执业政策说明/);
  assert.match(about, /国卫医发〔2014〕86号/);
  assert.match(about, /医联体帮扶/);
  assert.match(about, /data-about-flow="multi-practice"/);
  assert.match(about, /医师多点执业主要功能报告\.md/);
  assert.match(read("institution.html"), /政策说明/);
  assert.match(read("institution.js"), /电子化注册/);
  assert.match(read("institution.js"), /第一执业地点电子确认/);
  assert.match(read("institution.js"), /责任保险/);
  assert.match(read("institution.js"), /补正提示/);
  assert.match(read("institution.js"), /riskFlags/);
  assert.match(doc, /国卫医发〔2014〕86号/);
  assert.match(doc, /适用边界/);
  assert.match(doc, /政策到系统字段映射/);
  assert.match(doc, /角色操作清单/);
  assert.match(doc, /风险补正口径/);
  assert.match(doc, /documentChecks\.liabilityInsurance/);
  assert.match(doc, /医师电子化注册核验/);
  assert.match(doc, /第一执业地点电子确认/);
  assert.match(doc, /\/api\/multi-practice-registry/);
  assert.match(doc, /flowchart LR/);
  assert.match(doc, /医生账户只能查看本人多点执业申请/);
  assert.match(report, /医师多点执业主要功能报告/);
  assert.match(report, /主要功能矩阵/);
  assert.match(report, /三端功能边界/);
  assert.match(report, /multiPracticeSummary/);
  assert.match(report, /riskFlags/);
  assert.match(report, /doctorProfiles\.electronicRegistration/);
  assert.match(report, /primaryPracticeConfirmation/);
  assert.match(report, /\/api\/multi-practice-registry/);
  assert.match(report, /flowchart TD/);
  assert.match(report, /test\/api\.test\.js/);
});

test("static snapshot keeps completed P2 governance collections", () => {
  const data = JSON.parse(read("data/db.json"));
  assert.equal(data.creditEvaluationRules.version, "credit-rules-2026.1");
  assert.equal(Array.isArray(data.researchDatasets), true);
  assert.equal(data.researchDatasets.some((item) => item.id === "rd-hypertension-001"), true);
  assert.equal(data.researchDatasets.every((item) => item.ethicsStatus && item.deidentificationStatus && item.sandbox && Array.isArray(item.sourceCollections)), true);
  assert.equal(data.dataAccessLogs.some((item) => /research/i.test(`${item.scope || ""} ${item.purpose || ""}`)), true);
  assert.equal(Array.isArray(data.diseaseRegistryModels), true);
  assert.equal(data.diseaseRegistryModels.some((item) => item.id === "dm-hypertension-risk-v1"), true);
  assert.equal(Array.isArray(data.drugConsumableSupervisions), true);
  assert.equal(data.drugConsumableSupervisions.some((item) => item.id === "dcs-rational-r1" && item.boundary === "rational-medication"), true);
  assert.equal(data.drugConsumableSupervisions.some((item) => item.id === "dcs-consumable-mr1" && item.boundary === "consumable-clue"), true);
  assert.equal(data.mobileExperienceSettings.weakNetworkMode, "cache-last-state");
  assert.equal(Array.isArray(data.accessibilityChecklist), true);
  assert.equal(data.accessibilityChecklist.some((item) => item.id === "a11y-large-font"), true);
  assert.equal(Array.isArray(data.productionDeploymentPlan), true);
  assert.equal(data.productionDeploymentPlan.some((item) => item.id === "prod-storage-adapter"), true);
  assert.equal(Array.isArray(data.healthDashboardSnapshots), true);
  assert.equal(data.healthDashboardSnapshots.some((item) => item.sourceApplications.length === 7), true);
  assert.equal(Array.isArray(data.countyAcceptanceLedger), true);
  assert.equal(data.countyAcceptanceLedger.some((item) => item.id === "county-accept-report-return"), true);
  assert.equal(data.countyAcceptanceLedger.some((item) => item.metricKey === "criticalAlert"), true);
  assert.equal(Array.isArray(data.platformInterfaces), true);
  assert.equal(data.platformInterfaces.filter((item) => item.priority === "P0").every((item) => item.owner && item.status && item.next), true);
  assert.equal(data.platformInterfaces.filter((item) => item.priority === "P0").every((item) => item.status === "演示对接完成"), true);
  assert.equal(data.platformInterfaces.some((item) => item.id === "if-medical" && /HIS\/EMR\/LIS\/PACS/.test(item.existing)), true);
  assert.equal(data.platformCapabilities.some((item) => item.id === "cap-data-platform" && item.status === "演示底座闭环"), true);
  assert.equal(data.platformCapabilities.some((item) => item.id === "cap-evaluation" && item.status === "测评证据已建档"), true);
  assert.equal(data.platformCapabilities.some((item) => item.id === "cap-security" && item.status === "安全证据已建档"), true);
  assert.equal(data.applicationCatalog.some((item) => item.id === "app-institution" && item.status === "演示对接完成"), true);
  assert.equal(data.securityAcceptanceLedger.every((item) => item.id && item.category && item.owner && item.status && item.next), true);
  assert.equal(data.securityAcceptanceLedger.every((item) => /建档/.test(item.status)), true);
  assert.equal(data.platformRoadmap.filter((item) => item.priority === "P2").every((item) => item.status === "已完成"), true);
});

test("health dashboard exposes the aggregate application entry and API contract", () => {
  const html = read("health-dashboard.html");
  const js = read("health-dashboard.js");
  const server = read("server.js");
  const release = read("scripts/release-report.js");
  const deploy = read("scripts/deploy-check.js");

  assert.match(html, /卫生健康综合驾驶舱/);
  assert.match(html, /dashboard-applications/);
  assert.match(html, /dashboard-templates/);
  assert.match(html, /dashboard-actions/);
  assert.match(html, /dashboard-interfaces/);
  assert.match(html, /dashboard-evidence/);
  assert.match(html, /dashboard-dependencies/);
  assert.match(js, /\/api\/health-dashboard\/summary/);
  assert.match(js, /functionalBoundary/);
  assert.match(js, /renderTemplates/);
  assert.match(js, /source application/);
  assert.match(server, /\/api\/health-dashboard\/summary/);
  assert.match(server, /\/api\/priority-applications\/templates/);
  assert.match(server, /buildPriorityApplicationTemplates/);
  assert.match(server, /buildHealthDashboardSummary/);
  assert.match(release, /health-dashboard-summary/);
  assert.match(release, /\/api\/priority-applications\/templates/);
  assert.match(deploy, /snapshot:healthDashboard/);
});

test("about page documents maternal child module and unified template flow rule", () => {
  const about = read("about.html");
  const doc = read("docs/妇幼健康全模块说明.md");
  const templates = read("scripts/health-dashboard-summary.js");

  assert.match(about, /妇幼健康全模块/);
  assert.match(about, /data-about-flow="maternal-child"/);
  assert.match(about, /统一模板规则/);
  assert.match(doc, /flowchart TD/);
  assert.match(doc, /出生医学证明/);
  assert.match(doc, /统一模板规则/);
  assert.match(templates, /documentationRule/);
  assert.match(templates, /flowDiagram/);
});

test("maternal child about page documents policy basis and release evidence", () => {
  const page = read("maternal-child-about.html");
  const policy = read("docs/maternal-child-policy.md");
  const moduleDoc = read("docs/妇幼健康全模块说明.md");
  const readme = read("README.md");
  const deployment = read("DEPLOYMENT.md");
  const workflow = read(".github/workflows/ci.yml");

  assert.match(read("about.html"), /maternal-child-about\.html/);
  assert.match(page, /data-maternal-about="policy-basis"/);
  assert.match(page, /第七版出生医学证明/);
  assert.match(page, /data-about-flow="maternal-child-policy"/);
  assert.match(page, /卫健管理端/);
  assert.match(page, /医疗机构端/);
  assert.match(page, /个人用户端/);
  assert.match(policy, /卫妇社发〔2009〕96 号/);
  assert.match(policy, /国卫办妇幼发〔2023〕4 号/);
  assert.match(policy, /flowchart TD/);
  assert.match(moduleDoc, /政策依据摘要/);
  assert.match(readme, /maternal-child-about\.html/);
  assert.match(deployment, /maternal-child-policy\.md/);
  assert.match(workflow, /priority-apps:templates/);
});

test("static snapshot keeps acceptance evidence clean and actionable", () => {
  const raw = read("data/db.json");
  const data = JSON.parse(raw);
  assert.doesNotMatch(raw, /编码损坏，待核验/);
  assert.doesNotMatch(raw, /\?\?\?/);
  assert.doesNotMatch(raw, /�/);
  const interoperability = data.platformEvidence.find((item) => item.id === "ev-interoperability");
  assert.equal(interoperability.status, "已建档");
  assert.equal(interoperability.records.length >= 2, true);
  const security = data.platformEvidence.find((item) => item.id === "ev-security");
  assert.equal(security.status, "已建档");
  assert.equal(security.records.length >= 3, true);
  const launch = data.platformEvidence.find((item) => item.id === "ev-launch");
  assert.equal(launch.status, "演示验收建档");
  assert.equal(launch.records.length >= 3, true);
  assert.equal(interoperability.records.every((item) => item.owner && item.testRecord && item.status), true);
  assert.equal(security.records.every((item) => item.owner && item.testRecord && item.status), true);
  assert.equal(launch.records.every((item) => item.owner && item.testRecord && item.status), true);
  assert.equal(interoperability.records.some((item) => item.link === "/api/system/readiness"), true);
});

test("chronic disease policy module exposes 2025 service capacity workflow", () => {
  const data = JSON.parse(read("data/db.json"));
  const html = read("index.html");
  const app = read("app.js");
  const server = read("server.js");
  ["chronicServiceRoles", "chronicCapabilityConditions", "chronicServicePathways", "chronicComorbidityPlans", "chronicTcmServices", "chronicSelfManagement", "chronicMedicationSupport", "chronicQualityMetrics", "chronicAcceptanceLedger"].forEach((key) => {
    assert.equal(Array.isArray(data[key]), true, `${key} should be seeded`);
    assert.equal(data[key].length > 0, true, `${key} should not be empty`);
  });
  assert.equal(data.chronicAcceptanceLedger.some((item) => item.id === "chronic-accept-quality"), true);
  assert.equal(data.chronicAcceptanceLedger.some((item) => item.metricKey === "selfManagement"), true);
  ["chronic-service-roles", "chronic-capability-conditions", "chronic-service-pathways", "chronic-comorbidity-table", "chronic-tcm-services", "chronic-self-management", "chronic-medication-support", "chronic-quality-metrics"].forEach((id) => {
    assert.match(html, new RegExp(id), `${id} panel should be present`);
  });
  assert.match(html, /chronic-risk-summary/);
  assert.match(html, /chronic-risk-stratification/);
  assert.match(app, /renderChronicPolicyServices/);
  assert.match(app, /applyChronicWorkflowAction/);
  assert.match(app, /renderChronicRiskStratification/);
  assert.match(app, /buildChronicRiskStratification/);
  assert.match(app, /chronicComorbidityPlans/);
  assert.match(app, /chronicMedicationSupport/);
  assert.match(server, /chronic-comorbidity-plans/);
  assert.match(server, /\/api\/chronic\/acceptance-ledger/);
  assert.match(server, /\/api\/chronic\/risk-stratification/);
  assert.match(server, /buildChronicRiskStratification/);
  assert.match(server, /chronicMedicationSupport/);
  assert.match(server, /buildChronicServiceSummary/);
  assert.match(server, /buildCountyServiceSummary/);
  assert.match(server, /DEMO_TODAY/);
  assert.match(server, /2026-06-22/);
  assert.match(server, /changed && !shouldUseSqlite\(\)/);
  assert.match(server, /多病共管/);
  assert.match(server, /基层慢病健康管理中心/);
});

test("insurance portal exposes actionable drug consumable supervision workflow", () => {
  const html = read("insurance.html");
  const js = read("insurance.js");
  const server = read("server.js");
  assert.match(html, /drug-consumable-panel/);
  assert.match(js, /renderDrugConsumableSupervision/);
  assert.match(js, /postDrugConsumableAction/);
  assert.match(js, /data-drug-action/);
  assert.match(server, /buildDrugConsumableSupervision/);
  assert.match(server, /\/api\/drug-consumable-supervision/);
  assert.match(server, /drug-consumable-review/);
  assert.match(server, /drug-consumable-remediation/);
  assert.match(server, /drug-consumable-insurance-sync/);
});

test("deployment baseline documents scripts and environment template", () => {
  const pkg = JSON.parse(read("package.json"));
  assert.equal(Boolean(pkg.scripts["deploy:check"]), true);
  assert.equal(Boolean(pkg.scripts["env:check"]), true);
  assert.equal(Boolean(pkg.scripts["release:report"]), true);
  assert.equal(Boolean(pkg.scripts["release:manifest"]), true);
  assert.equal(Boolean(pkg.scripts["priority-apps:templates"]), true);
  assert.equal(Boolean(pkg.scripts["maternal-child:readiness"]), true);
  assert.equal(Boolean(pkg.scripts["rollback:snapshot"]), true);
  assert.equal(Boolean(pkg.scripts["storage:inspect"]), true);
  assert.equal(Boolean(pkg.scripts["identity:contract"]), true);
  assert.equal(Boolean(pkg.scripts["audit:retention"]), true);
  assert.equal(Boolean(pkg.scripts["chronic:followup-readiness"]), true);
  assert.equal(Boolean(pkg.scripts["data-quality:report"]), true);
  assert.equal(Boolean(pkg.scripts["quality-safety:report"]), true);
  assert.equal(Boolean(pkg.scripts["drug-consumable:readiness"]), true);
  assert.equal(Boolean(pkg.scripts["environment:matrix"]), true);
  assert.equal(Boolean(pkg.scripts["hospital-operations:readiness"]), true);
  assert.equal(Boolean(pkg.scripts["integration:readiness"]), true);
  assert.equal(Boolean(pkg.scripts["interface:mapping"]), true);
  assert.equal(Boolean(pkg.scripts["regional-data-sharing:report"]), true);
  assert.equal(Boolean(pkg.scripts["research:sandbox"]), true);
  assert.equal(Boolean(pkg.scripts["monitoring:readiness"]), true);
  assert.equal(Boolean(pkg.scripts["referral:readiness"]), true);
  assert.equal(Boolean(pkg.scripts["operations:readiness"]), true);
  assert.equal(Boolean(pkg.scripts["process:audit"]), true);
  assert.equal(Boolean(pkg.scripts["site:pack"]), true);
  assert.equal(Boolean(pkg.scripts["production-db:readiness"]), true);
  assert.equal(Boolean(pkg.scripts["evaluation:evidence"]), true);
  assert.match(read(".env.example"), /SESSION_SECRETS=/);
  assert.match(read(".env.example"), /INTEGRATION_GATEWAY_SECRET=/);
  assert.match(read(".env.example"), /CUTOVER_SITE_INTERFACE_SIGNOFF/);
  assert.match(read(".env.example"), /CUTOVER_DR_REHEARSAL_SIGNOFF/);
  assert.match(read(".env.example"), /OIDC_ISSUER_URL=/);
  assert.match(read(".env.example"), /AUDIT_EXPORT_PATH=/);
  assert.match(read("README.md"), /\/api\/health/);
  assert.match(read("README.md"), /deploy:check/);
  assert.match(read("README.md"), /release:report/);
  assert.match(read("README.md"), /release:manifest/);
  assert.match(read("scripts/release-report.js"), /test:coverage/);
  assert.match(read("scripts/release-report.js"), /test:e2e/);
  assert.match(read("scripts/release-report.js"), /Production cutover checklist/);
  assert.match(read("README.md"), /production-cutover-checklist\.md/);
  assert.match(read("README.md"), /storage-model-inspection\.md/);
  assert.match(read("README.md"), /identity-contract\.md/);
  assert.match(read("README.md"), /audit-retention-report\.md/);
  assert.match(read("docs/chronic-followup-readiness.md"), /chronic-followup-readiness-report\.md/);
  assert.match(read("docs/chronic-followup-readiness.md"), /\/api\/chronic\/followup-feedback/);
  assert.match(read("README.md"), /data-quality-report\.md/);
  assert.match(read("README.md"), /quality-safety-report\.md/);
  assert.match(read("README.md"), /drug-consumable-readiness-report\.md/);
  assert.match(read("README.md"), /environment-matrix-report\.md/);
  assert.match(read("README.md"), /integration-readiness-report\.md/);
  assert.match(read("README.md"), /interface-mapping-report\.md/);
  assert.match(read("scripts/release-report.js"), /regional-data-sharing-report\.md/);
  assert.match(read("README.md"), /research-sandbox-readiness-report\.md/);
  assert.match(read("README.md"), /monitoring-readiness-report\.md/);
  assert.match(read("README.md"), /operations-readiness-report\.md/);
  assert.match(read("README.md"), /hospital-operations-readiness-report\.md/);
  assert.match(read("README.md"), /process-audit-report\.md/);
  assert.match(read("README.md"), /service-acceptance-summary\.md/);
  assert.match(read("README.md"), /\/api\/service-acceptance-summary/);
  assert.match(read("README.md"), /site-readiness-pack\.md/);
  assert.match(read("README.md"), /release\/templates\/\*\/README\.md/);
  assert.match(read("README.md"), /\/api\/site-template-readmes/);
  assert.match(read("README.md"), /production-db-readiness-report\.md/);
  assert.match(read("README.md"), /evaluation-evidence-report\.md/);
  assert.match(read("README.md"), /release-artifact-manifest\.md/);
  assert.match(read("README.md"), /priority-application-templates\.md/);
  assert.match(read("DEPLOYMENT.md"), /storage-model-inspection\.md/);
  assert.match(read("DEPLOYMENT.md"), /identity-contract\.md/);
  assert.match(read("DEPLOYMENT.md"), /audit-retention-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /data-quality-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /quality-safety-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /drug-consumable-readiness-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /environment-matrix-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /integration-readiness-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /interface-mapping-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /research-sandbox-readiness-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /monitoring-readiness-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /operations-readiness-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /hospital-operations-readiness-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /process-audit-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /site-readiness-pack\.md/);
  assert.match(read("DEPLOYMENT.md"), /release\/templates\/\*\/README\.md/);
  assert.match(read("DEPLOYMENT.md"), /\/api\/site-template-readmes/);
  assert.match(read("DEPLOYMENT.md"), /service-acceptance-summary\.md/);
  assert.match(read("DEPLOYMENT.md"), /\/api\/service-acceptance-summary/);
  assert.match(read("DEPLOYMENT.md"), /production-db-readiness-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /evaluation-evidence-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /release-artifact-manifest\.md/);
  assert.match(read("DEPLOYMENT.md"), /priority-application-templates\.md/);
  assert.match(read("scripts/deploy-check.js"), /test:coverage/);
  assert.match(read("scripts/deploy-check.js"), /test:e2e/);
  assert.match(read("scripts/deploy-check.js"), /audit/);
  assert.match(read("scripts/deploy-check.js"), /identity:contract/);
  assert.match(read("scripts/deploy-check.js"), /audit:retention/);
  assert.match(read("scripts/deploy-check.js"), /chronic:followup-readiness/);
  assert.match(read("scripts/deploy-check.js"), /chronicFollowupStatusPolicy/);
  assert.match(read("scripts/deploy-check.js"), /data-quality:report/);
  assert.match(read("scripts/deploy-check.js"), /quality-safety:report/);
  assert.match(read("scripts/deploy-check.js"), /drug-consumable:readiness/);
  assert.match(read("scripts/deploy-check.js"), /environment:matrix/);
  assert.match(read("scripts/deploy-check.js"), /integration:readiness/);
  assert.match(read("scripts/deploy-check.js"), /interface:mapping/);
  assert.match(read("scripts/deploy-check.js"), /regional-data-sharing:report/);
  assert.match(read("scripts/deploy-check.js"), /monitoring:readiness/);
  assert.match(read("scripts/deploy-check.js"), /referral:readiness/);
  assert.match(read("scripts/deploy-check.js"), /operations:readiness/);
  assert.match(read("scripts/deploy-check.js"), /hospital-operations:readiness/);
  assert.match(read("scripts/deploy-check.js"), /process:audit/);
  assert.match(read("scripts/deploy-check.js"), /site:pack/);
  assert.match(read("scripts/deploy-check.js"), /release:manifest/);
  assert.match(read("scripts/deploy-check.js"), /priority-apps:templates/);
  assert.match(read("scripts/deploy-check.js"), /maternal-child:readiness/);
  assert.match(read("docs/妇幼健康主要功能报告.md"), /## 主要功能矩阵/);
  assert.match(read("docs/妇幼健康主要功能报告.md"), /maternal-child-readiness-report\.md/);
  assert.match(read("scripts/deploy-check.js"), /production-db:readiness/);
  assert.match(read("scripts/deploy-check.js"), /evaluation:evidence/);
  assert.match(read("scripts/deploy-check.js"), /process\.platform === "win32" \? "npm\.cmd" : "npm"/);
  assert.match(read(".github/workflows/ci.yml"), /npm run deploy:check/);
  assert.match(read(".github/workflows/ci.yml"), /npm run storage:inspect/);
  assert.match(read(".github/workflows/ci.yml"), /npm run identity:contract/);
  assert.match(read(".github/workflows/ci.yml"), /npm run audit:retention/);
  assert.match(read(".github/workflows/ci.yml"), /npm run chronic:followup-readiness/);
  assert.match(read(".github/workflows/ci.yml"), /npm run data-quality:report/);
  assert.match(read(".github/workflows/ci.yml"), /npm run quality-safety:report/);
  assert.match(read(".github/workflows/ci.yml"), /npm run drug-consumable:readiness/);
  assert.match(read(".github/workflows/ci.yml"), /npm run integration:readiness/);
  assert.match(read(".github/workflows/ci.yml"), /npm run interface:mapping/);
  assert.match(read(".github/workflows/ci.yml"), /npm run regional-data-sharing:report/);
  assert.match(read(".github/workflows/ci.yml"), /npm run monitoring:readiness/);
  assert.match(read(".github/workflows/ci.yml"), /npm run referral:readiness/);
  assert.match(read("institution.html"), /teleconsultation-loop/);
  assert.match(read("county.html"), /county-teleconsultation-loop/);
  assert.match(read(".github/workflows/ci.yml"), /npm run operations:readiness/);
  assert.match(read(".github/workflows/ci.yml"), /npm run site:pack/);
  assert.match(read(".github/workflows/ci.yml"), /npm run production-db:readiness/);
  assert.match(read(".github/workflows/ci.yml"), /npm run evaluation:evidence/);
  assert.match(read(".github/workflows/ci.yml"), /npm run release:manifest/);
  assert.match(read(".github/workflows/ci.yml"), /npm run priority-apps:templates/);
  assert.match(read(".github/workflows/ci.yml"), /npm run maternal-child:readiness/);
  assert.match(read(".github/workflows/ci.yml"), /npm run release:report/);
  assert.match(read(".github/workflows/ci.yml"), /actions\/upload-artifact@v4/);
  assert.match(read(".github/workflows/ci.yml"), /release-readiness-report/);
  assert.match(read(".github/workflows/ci.yml"), /npm audit --omit=dev/);
});

test("regional data sharing application has runnable entry, API and evidence script", () => {
  const html = read("regional-data-sharing.html");
  const client = read("regional-data-sharing.js");
  const server = read("server.js");
  const script = read("scripts/regional-data-sharing.js");
  const data = JSON.parse(read("data/db.json"));

  assert.match(html, /区域诊疗数据共享平台/);
  assert.match(html, /regional-data-sharing\.js/);
  assert.match(client, /\/api\/regional-data-sharing/);
  assert.match(client, /调阅留痕/);
  assert.match(server, /seedRegionalDataSharingScope/);
  assert.match(server, /createRegionalSharingAccessReview/);
  assert.match(server, /\/api\/regional-data-sharing\/access-reviews/);
  assert.match(script, /buildRegionalDataSharingReport/);
  assert.equal(data.regionalDataSharingScope.reusedCollections.includes("residents"), true);
  assert.equal(data.regionalDataSharingScope.exclusions.length >= 3, true);
  assert.equal(data.regionalSharingPackages.length >= 3, true);
  assert.equal(data.regionalSharingPackages.every((item) => ["ready", "pending_review", "blocked", "archived"].includes(item.status)), true);
});

test("platform and workbench expose P2 governance and runtime panels", () => {
  const platformHtml = read("platform.html");
  const platformJs = read("platform.js");
  const workbenchHtml = read("workbench.html");
  const workbenchJs = read("workbench.js");
  const operationsHtml = read("operations.html");
  const operationsJs = read("operations.js");
  assert.match(platformHtml, /research-governance/);
  assert.match(platformJs, /runResearchDatasetAction/);
  assert.match(platformJs, /sandbox-access/);
  assert.match(platformJs, /outcome-return/);
  assert.match(platformHtml, /mobile-accessibility-governance/);
  assert.match(platformHtml, /production-deployment-plan/);
  assert.match(platformJs, /renderResearchGovernance/);
  assert.match(platformJs, /renderMobileAccessibilityGovernance/);
  assert.match(platformJs, /renderProductionDeploymentPlan/);
  assert.match(platformJs, /evr-interoperability-contracts/);
  assert.match(platformJs, /integration-readiness-report\.md/);
  assert.match(platformJs, /audit-retention-report\.md/);
  assert.match(platformJs, /HIS\/EMR\/LIS\/PACS 契约和网关模拟接入/);
  assert.doesNotMatch(platformJs, /domain: "统一认证"[^\n]*status: "开发中"/);
  assert.doesNotMatch(platformJs, /domain: "医疗机构业务系统"[^\n]*status: "待接口"/);
  assert.match(workbenchHtml, /system-readiness/);
  assert.match(workbenchHtml, /release-evidence-gates/);
  assert.match(workbenchHtml, /acceptance-ledgers/);
  assert.match(workbenchHtml, /site-readiness-pack/);
  assert.match(workbenchJs, /loadOperationalMetrics/);
  assert.match(workbenchJs, /loadSystemReadiness/);
  assert.match(workbenchJs, /loadAcceptanceLedgers/);
  assert.match(workbenchJs, /loadServiceAcceptanceSummary/);
  assert.match(workbenchJs, /data-service-open-action/);
  assert.match(workbenchJs, /loadSiteReadinessPack/);
  assert.match(workbenchJs, /loadSiteTemplateReadmes/);
  assert.match(workbenchJs, /loadReleaseReport/);
  assert.match(workbenchJs, /loadProductionCutoverChecklist/);
  assert.match(workbenchJs, /loadReleaseArtifactManifest/);
  assert.match(workbenchJs, /loadUnifiedTaskReport/);
  assert.match(workbenchJs, /data-unified-task/);
  assert.match(workbenchJs, /renderReleaseEvidenceGates/);
  assert.match(workbenchJs, /data-quality:report/);
  assert.match(workbenchJs, /operations:readiness/);
  assert.match(workbenchJs, /process:audit/);
  assert.match(workbenchJs, /service:acceptance/);
  assert.match(workbenchJs, /site:pack/);
  assert.match(workbenchJs, /release:manifest/);
  assert.match(workbenchJs, /production:cutover/);
  assert.match(workbenchJs, /evaluation:evidence/);
  assert.match(read("server.js"), /release-artifact-manifest/);
  assert.match(workbenchJs, /\/api\/metrics/);
  assert.match(workbenchJs, /\/api\/system\/readiness/);
  assert.match(workbenchJs, /\/api\/process-audit/);
  assert.match(workbenchJs, /\/api\/service-acceptance-summary/);
  assert.match(workbenchJs, /\/api\/site-readiness-pack/);
  assert.match(workbenchJs, /\/api\/site-template-readmes/);
  assert.match(workbenchJs, /\/api\/release-report/);
  assert.match(workbenchJs, /\/api\/production-cutover-checklist/);
  assert.match(workbenchJs, /\/api\/release-artifact-manifest/);
  assert.match(workbenchJs, /\/api\/tasks/);
  assert.match(workbenchJs, /\/api\/chronic\/acceptance-ledger/);
  assert.match(workbenchJs, /\/api\/county\/acceptance-ledger/);
  assert.match(read("server.js"), /\/api\/process-audit/);
  assert.match(read("server.js"), /\/api\/service-acceptance-summary/);
  assert.match(read("server.js"), /\/api\/site-readiness-pack/);
  assert.match(read("server.js"), /SERVICE_DOMAIN_BY_COLLECTION/);
  assert.match(read("server.js"), /priorityLevel/);
  assert.match(read("server.js"), /\/api\/site-template-readmes/);
  assert.match(read("server.js"), /\/api\/release-report/);
  assert.match(read("server.js"), /\/api\/production-cutover-checklist/);
  assert.match(read("server.js"), /\/api\/release-artifact-manifest/);
  assert.match(operationsHtml, /operations-snapshots/);
  assert.match(operationsHtml, /dispatch-form/);
  assert.match(operationsHtml, /reconciliation-reviews/);
  assert.match(operationsJs, /fetchOperationsDashboard/);
  assert.match(operationsJs, /\/operations\/dashboard/);
  assert.match(operationsJs, /\/operations\/dispatch/);
  assert.match(operationsJs, /\/operations\/reconciliation/);
  assert.match(read("server.js"), /\/api\/operations\/dashboard/);
  assert.match(read("server.js"), /operations-dispatch/);
  assert.match(read("server.js"), /statistics-reconciliation-review/);
});

test("quality safety supervision app exposes runnable portal, API and release evidence", () => {
  const data = JSON.parse(read("data/db.json"));
  const html = read("quality-safety.html");
  const js = read("quality-safety.js");
  const server = read("server.js");
  ["qualitySafetyEvents", "criticalValueAlerts", "clinicalPathwayCases", "medicalRecordQualityReviews", "mutualRecognitionQualityReviews", "qualityRectificationOrders"].forEach((key) => {
    assert.equal(Array.isArray(data[key]), true, `${key} should be seeded`);
    assert.equal(data[key].length > 0, true, `${key} should not be empty`);
  });
  ["diagnosticReports", "countyMutualRecognitionRecords", "dataQualityIssues", "institutionCreditEvaluations", "securityEvents", "hospitalInteroperabilityFunctions"].forEach((key) => {
    assert.match(read("scripts/quality-safety-report.js"), new RegExp(key));
  });
  assert.match(html, /quality-safety-metrics/);
  assert.match(html, /quality-safety-issues/);
  assert.match(html, /quality-safety-rectifications/);
  assert.match(js, /loadQualitySafety/);
  assert.match(js, /dispatchIssue/);
  assert.match(js, /submitFeedback/);
  assert.match(js, /reviewOrder/);
  assert.match(server, /\/api\/quality-safety\/dashboard/);
  assert.match(server, /\/api\/quality-safety\/issues\/:id\/dispatch/);
  assert.match(server, /\/api\/quality-safety\/rectifications\/:id\/feedback/);
  assert.match(server, /\/api\/quality-safety\/rectifications\/:id\/review/);
  assert.match(read("scripts/release-report.js"), /qualitySafety:report/);
  assert.match(read("platform.html"), /quality-safety\.html/);
  assert.match(read("workbench.html"), /quality-safety\.html/);
  assert.match(read("auth.js"), /quality-safety\.html/);
  assert.match(read("server.js"), /\/api\/chronic\/followup-summary/);
  assert.match(read("server.js"), /\/api\/chronic\/followup-feedback/);
  assert.match(read("server.js"), /\/api\/chronic\/followup-dispatch/);
  assert.match(read("institution.html"), /chronic-followup-workbench/);
  assert.match(read("institution.js"), /dispatchChronicFollowup/);
  assert.match(read("citizen.html"), /followup-feedback-form/);
  assert.match(read("citizen.js"), /bindFollowupFeedback/);
});

test("system structure documentation reflects completed local governance loops", () => {
  const systemDoc = read("docs/慢病平台系统结构图与优化建议.md");
  assert.match(systemDoc, /后续优先级边界/);
  assert.match(systemDoc, /本地已完成签名会话、接口级权限/);
  assert.match(systemDoc, /已完成 HIS\/EMR\/LIS\/PACS\/医保\/证照\/统计契约/);
  assert.match(systemDoc, /生产切换证据深化/);
});

test("citizen portal exposes P1 record details trends and source labels", () => {
  const citizenHtml = read("citizen.html");
  const citizenJs = read("citizen.js");
  const citizenCss = read("citizen.css");
  assert.match(citizenHtml, /citizen-trend-grid/);
  assert.match(citizenJs, /renderHealthTrends/);
  assert.match(citizenJs, /buildCitizenTrendSeries/);
  assert.match(citizenJs, /renderCitizenTrend/);
  assert.match(citizenJs, /record-detail/);
  assert.match(citizenJs, /renderSourceBadge/);
  assert.match(citizenJs, /classifyDataSource/);
  assert.match(citizenCss, /citizen-trend-card/);
  assert.match(citizenCss, /source-badge/);
  assert.match(citizenCss, /record-detail/);
});

test("citizen portal exposes PWA install and offline shell assets", () => {
  const citizenHtml = read("citizen.html");
  const citizenJs = read("citizen.js");
  const mobilePreviewHtml = read("mobile-preview.html");
  const mobilePreviewCss = read("mobile-preview.css");
  const manifest = JSON.parse(read("manifest.webmanifest"));
  const serviceWorker = read("service-worker.js");
  assert.match(citizenHtml, /rel="manifest"/);
  assert.match(citizenHtml, /serviceWorker\.register\("\.\/service-worker\.js"\)/);
  assert.match(citizenHtml, /citizen\.js\?v=20260628launch/);
  assert.match(citizenHtml, /mobile-web-app-capable/);
  assert.match(citizenHtml, /apple-mobile-web-app-capable/);
  assert.match(citizenHtml, /apple-mobile-web-app-title/);
  assert.match(citizenHtml, /apple-touch-icon/);
  assert.match(citizenHtml, /auth\.js\?v=20260627/);
  assert.match(mobilePreviewHtml, /preview=mobile-nav/);
  assert.match(mobilePreviewHtml, /http:\/\/localhost:5174\/mobile-preview\.html/);
  assert.match(mobilePreviewHtml, /DEMO-MOBILE-R1 \/ 888888/);
  assert.match(mobilePreviewHtml, /citizen\.html\?preview=mobile-nav&client=mini-program&page=health-record/);
  assert.match(mobilePreviewHtml, /data-preview-client="mini-program"/);
  assert.match(mobilePreviewHtml, /data-preview-client="app"/);
  assert.match(mobilePreviewHtml, /URLSearchParams\(location\.search\)/);
  assert.match(mobilePreviewHtml, /previewParams\.get\("client"\)/);
  assert.match(mobilePreviewHtml, /setPreviewClient\(activePreviewClient, \{ syncUrl: false \}\)/);
  assert.match(mobilePreviewHtml, /internet-nursing\.html\?preview=mobile-nursing/);
  assert.match(mobilePreviewHtml, /client=\$\{activePreviewClient\}/);
  assert.match(mobilePreviewHtml, /page=\$\{service\}/);
  assert.match(mobilePreviewHtml, /data-preview-service="nursing"/);
  assert.match(mobilePreviewHtml, /data-preview-service="registration"/);
  assert.match(mobilePreviewHtml, /preview-refresh/);
  assert.match(mobilePreviewHtml, /postMessage/);
  assert.match(citizenJs, /set-service-tab/);
  assert.match(mobilePreviewCss, /preview-steps/);
  assert.match(mobilePreviewCss, /preview-client-switch/);
  assert.match(mobilePreviewCss, /preview-service-switch/);
  assert.match(mobilePreviewCss, /position: sticky/);
  assert.match(mobilePreviewCss, /grid-template-columns: minmax\(280px, 420px\) minmax\(390px, 430px\)/);
  assert.match(mobilePreviewCss, /max-width: 820px/);
  assert.match(mobilePreviewCss, /height: min\(760px, calc\(100vh - 132px\)\)/);
  assert.equal(manifest.start_url, "./citizen.html");
  assert.equal(manifest.id, "./citizen.html?client=app");
  assert.equal(manifest.display, "standalone");
  assert.deepEqual(manifest.display_override, ["standalone", "minimal-ui", "browser"]);
  assert.equal(manifest.prefer_related_applications, false);
  assert.equal(manifest.icons.some((item) => item.src === "./pwa-icon.svg"), true);
  assert.equal(manifest.shortcuts.some((item) => item.url === "./citizen.html?client=app&page=health-record#service-health-record"), true);
  assert.equal(manifest.shortcuts.some((item) => item.url === "./citizen.html?client=app&page=emr#service-emr"), true);
  assert.equal(manifest.shortcuts.some((item) => item.url === "./citizen.html?client=app&page=escort#service-escort"), true);
  assert.equal(manifest.shortcuts.some((item) => item.url === "./mobile-preview.html?client=app"), true);
  assert.match(serviceWorker, /CACHE_NAME/);
  assert.match(serviceWorker, /chronic-care-citizen-v13/);
  assert.match(serviceWorker, /citizen\.js\?v=20260627preview/);
  assert.match(serviceWorker, /citizen\.js\?v=20260627pages/);
  assert.match(serviceWorker, /citizen\.js\?v=20260627pages2/);
  assert.match(serviceWorker, /citizen\.js\?v=20260627actions/);
  assert.match(serviceWorker, /citizen\.js\?v=20260627channels/);
  assert.match(serviceWorker, /citizen\.js\?v=20260628launch/);
  assert.match(serviceWorker, /citizen\.html/);
  assert.match(serviceWorker, /mobile-preview\.html/);
  assert.match(serviceWorker, /mobile-preview\.css/);
  assert.match(serviceWorker, /data\/db\.json/);
  assert.match(serviceWorker, /\?:html\|js\|css/);
  assert.match(read("package.json"), /node --check service-worker\.js/);
  assert.match(read("README.md"), /manifest\.webmanifest/);
  assert.match(read("README.md"), /service-worker\.js/);
});

test("citizen portal exposes P2 imaging and attachment archive categories", () => {
  const citizenHtml = read("citizen.html");
  const citizenJs = read("citizen.js");
  assert.match(citizenHtml, /value="imaging"/);
  assert.match(citizenHtml, /value="attachments"/);
  assert.match(citizenJs, /key: "imaging"/);
  assert.match(citizenJs, /key: "attachments"/);
  assert.match(citizenJs, /PACS/);
  assert.match(citizenJs, /attachmentType/);
  assert.match(citizenJs, /renderAttachmentMeta/);
  assert.match(read("citizen.css"), /attachment-meta/);
  assert.match(citizenJs, /buildHealthTimeline\(archive, records, labs, medications, allergies, vaccines, admissions, imaging, attachments\)/);
  assert.match(read("README.md"), /影像资料和附件资料/);
  assert.match(read("docs/C端全流程审计与优化清单.md"), /PWA manifest/);
  assert.match(read("docs/C端全流程审计与优化清单.md"), /影像资料、附件资料/);
});

test("citizen portal exposes medical escort appointment workflow", () => {
  const citizenHtml = read("citizen.html");
  const citizenJs = read("citizen.js");
  const citizenCss = read("citizen.css");
  assert.match(citizenHtml, /escort-appointment-form/);
  assert.match(citizenHtml, /助医陪诊预约/);
  assert.match(citizenJs, /fetchCitizenEscortDashboard/);
  assert.match(citizenJs, /bindEscortAppointment/);
  assert.match(citizenJs, /\/escort-services\/orders/);
  assert.match(citizenCss, /escort-appointment-layout/);
  assert.match(citizenCss, /escort-order-card/);
  assert.match(read("server.js"), /provider is not published/);
});

test("citizen portal exposes resident service tabs and implementation states", () => {
  const loginHtml = read("login.html");
  const auth = read("auth.js");
  const citizenHtml = read("citizen.html");
  const citizenJs = read("citizen.js");
  const citizenCss = read("citizen.css");
  const server = read("server.js");
  assert.match(loginHtml, /phone-login-form/);
  assert.match(loginHtml, /手机号验证码/);
  assert.match(auth, /loginByPhone/);
  assert.match(auth, /demoSmsCode/);
  assert.match(server, /\/api\/auth\/phone-login/);
  assert.match(server, /findCitizenAuthUserByPhone/);
  ["健康档案", "电子病历", "护理", "陪诊", "挂号"].forEach((label) => assert.match(citizenJs, new RegExp(label)));
  assert.match(citizenHtml, /service-tabs/);
  assert.match(citizenHtml, /mobile-service-nav/);
  assert.match(citizenHtml, /service-summary/);
  assert.match(citizenHtml, /client-channel-panel/);
  assert.match(citizenHtml, /client-channel-switch/);
  assert.match(citizenHtml, /client-channel-detail/);
  assert.match(citizenHtml, /service-page-content/);
  assert.match(citizenHtml, /resident-function-audit/);
  assert.match(citizenHtml, /data-service-pane="health-record"/);
  assert.match(citizenHtml, /data-service-pane="registration"/);
  assert.match(citizenHtml, /feature-state ready/);
  assert.match(citizenHtml, /feature-state pending/);
  assert.ok(citizenHtml.indexOf("service-page-content") < citizenHtml.indexOf('data-service-pane="health-record"'));
  assert.ok(citizenHtml.indexOf("resident-function-audit") > citizenHtml.indexOf('data-service-pane="emr"'));
  assert.match(citizenJs, /citizenServiceTabs/);
  assert.match(citizenJs, /citizenClientChannels/);
  assert.match(citizenJs, /CLIENT_CHANNEL_KEY/);
  assert.match(citizenJs, /renderClientChannels/);
  assert.match(citizenJs, /setClientChannel/);
  assert.match(citizenJs, /clientChannelFromRoute/);
  assert.match(citizenJs, /clientChannelEntry/);
  assert.match(citizenJs, /copyClientEntry/);
  assert.match(citizenJs, /data-copy-client-entry/);
  assert.match(citizenJs, /launchChecklist/);
  assert.match(citizenJs, /client-launch-checklist/);
  assert.match(citizenJs, /data-client-channel/);
  assert.match(citizenJs, /mini-program/);
  assert.match(citizenJs, /app/);
  assert.match(citizenJs, /小程序/);
  assert.match(citizenJs, /APP/);
  assert.match(citizenJs, /renderMobileServiceNav/);
  assert.match(citizenJs, /data-mobile-service-tab/);
  assert.match(citizenJs, /citizenPageHref/);
  assert.match(citizenJs, /serviceTabFromRoute/);
  assert.match(citizenJs, /params\.set\("page", key\)/);
  assert.match(citizenJs, /pushState/);
  assert.match(citizenJs, /aria-current/);
  assert.match(citizenJs, /title:/);
  assert.match(citizenJs, /actionLabel/);
  assert.match(citizenJs, /service-page-action/);
  assert.match(citizenJs, /data-service-action/);
  assert.match(citizenJs, /internet-nursing\.html/);
  assert.match(citizenJs, /getServicePageTarget/);
  assert.match(citizenJs, /scrollToPane/);
  assert.match(citizenJs, /residentFunctionAudit/);
  assert.match(citizenJs, /renderResidentFunctionAudit/);
  assert.match(citizenJs, /手机号验证码登录/);
  assert.match(citizenJs, /长期照护评估/);
  assert.match(citizenJs, /医院号源查询/);
  assert.match(citizenJs, /serviceTabFromHash/);
  assert.match(citizenJs, /setServiceTab/);
  assert.match(citizenJs, /renderServiceSummary/);
  assert.match(citizenJs, /hashchange/);
  assert.match(citizenJs, /popstate/);
  assert.match(citizenJs, /updateServicePanes/);
  assert.match(citizenCss, /resident-audit-grid/);
  assert.match(citizenCss, /mobile-service-nav/);
  assert.match(citizenCss, /\.service-tabs a/);
  assert.match(citizenCss, /\.mobile-service-nav a/);
  assert.match(citizenCss, /service-page-content-anchor/);
  assert.match(citizenCss, /service-summary-actions/);
  assert.match(citizenCss, /service-page-action/);
  assert.match(citizenCss, /client-channel-panel/);
  assert.match(citizenCss, /client-channel-switch/);
  assert.match(citizenCss, /client-channel-grid/);
  assert.match(citizenCss, /client-channel-actions/);
  assert.match(citizenCss, /client-channel-action/);
  assert.match(citizenCss, /client-launch-checklist/);
  assert.match(citizenCss, /position: fixed/);
  assert.match(citizenCss, /safe-area-inset-bottom/);
  assert.match(citizenCss, /resident-audit-card:not\(\.active\)/);
  assert.match(citizenCss, /grid-auto-columns: minmax\(156px, 72vw\)/);
  assert.match(citizenCss, /scroll-snap-type: x mandatory/);
  assert.match(citizenCss, /min-height: 44px/);
  assert.match(citizenCss, /service-status-card/);
  assert.match(citizenCss, /service-summary-stats/);
});

test("internet nursing module exposes appointment, management and nurse workflows", () => {
  const html = read("internet-nursing.html");
  const js = read("internet-nursing.js");
  const css = read("portal.css");
  const mobilePreviewHtml = read("mobile-preview.html");
  const server = read("server.js");
  assert.match(html, /nursing-appointment-form/);
  assert.match(html, /nursing-orders/);
  assert.match(html, /nursing-nurse-queue/);
  assert.match(html, /nursing-risk-guidance/);
  assert.match(html, /nursing-service-select/);
  assert.match(html, /nursing-mobile-workbench/);
  assert.match(html, /data-mobile-surface="citizen-appointment"/);
  assert.match(html, /data-mobile-surface="nurse-response"/);
  assert.match(html, /nursing-mobile-appointment/);
  assert.match(html, /nursing-nurse-mobile/);
  assert.match(js, /fetchInternetNursingDashboard/);
  assert.match(js, /renderRiskGuidance/);
  assert.match(js, /nextNursingAction/);
  assert.match(js, /renderMobileAppointmentStatus/);
  assert.match(js, /renderMobileNurseCards/);
  assert.match(js, /renderServiceItemSelect/);
  assert.match(js, /bindNurseActionButtons/);
  assert.match(js, /sourceChannel = "internet-nursing-mobile"/);
  assert.match(js, /nurseActionButtons/);
  assert.match(js, /showNursingMessage/);
  assert.match(js, /\/internet-nursing\/orders/);
  assert.match(js, /currentNursingUser/);
  assert.match(js, /accountType !== "nurse"/);
  assert.match(js, /accountType === "nurse"/);
  assert.match(js, /select\.disabled = Boolean\(sessionNurseId\)/);
  assert.match(js, /仅查看/);
  assert.match(js, /需医院派单/);
  assert.match(html, /互联网\+护理服务/);
  assert.match(html, /个人端预约/);
  assert.match(html, /医院端管理/);
  assert.match(html, /护士端接单/);
  assert.match(html, /手机端预约/);
  assert.match(html, /手机端接单/);
  assert.match(css, /nursing-mobile-workbench/);
  assert.match(css, /nursing-mobile-card/);
  assert.match(css, /nursing-desktop-table/);
  assert.match(mobilePreviewHtml, /internet-nursing\.html\?preview=mobile-nursing/);
  assert.match(server, /\/api\/internet-nursing\/dashboard/);
  assert.match(server, /canAccessInternetNursingOrder/);
  assert.match(server, /validateInternetNursingAppointment/);
  assert.match(server, /buildInternetNursingActionMessage/);
  assert.match(server, /互联网护理新预约/);
  assert.match(server, /assertInternetNursingActionAllowed/);
  assert.match(server, /nurse can only operate assigned orders/);
  assert.match(read("auth.js"), /"internet-nursing\.html": \["commission", "institution", "citizen", "county"\]/);
  assert.match(read("auth.js"), /username: "nurse"/);
  assert.match(read("auth.js"), /password: "123456"/);
  assert.match(read("auth.js"), /护士工作站/);
  assert.match(read("auth.js"), /互联网护理/);
  assert.match(read("auth.js"), /displayAuthText/);
  assert.match(read("server.js"), /username: "nurse"/);
  assert.match(read("server.js"), /password: "123456"/);
  assert.match(read("server.js"), /护士工作站/);
  assert.match(read("package.json"), /internet-nursing:readiness/);
  assert.match(read("scripts/release-artifact-manifest.js"), /internet-nursing-readiness-report\.md/);
  assert.match(read("scripts/release-report.js"), /buildInternetNursingReadinessReport/);
  assert.match(read(".github/workflows/ci.yml"), /npm run internet-nursing:readiness/);
  assert.match(read("README.md"), /Internet Nursing Pilot/);
  assert.match(read("DEPLOYMENT.md"), /internet-nursing:readiness/);
  assert.match(read("docs/互联网护理服务模块说明.md"), /flowchart TD/);
  assert.match(read("docs/互联网护理服务模块说明.md"), /nurse \/ 123456/);
  assert.match(read("docs/互联网护理服务模块说明.md"), /\/api\/internet-nursing\/orders\/:id\/actions/);
  assert.match(read("docs/互联网护理服务模块说明.md"), /互联网护理上线与下一步开发计划/);
  assert.match(read("docs/互联网护理上线与下一步开发计划.md"), /上线标准/);
  assert.match(read("docs/互联网护理上线与下一步开发计划.md"), /下一步开发计划/);
  assert.doesNotMatch(html, /Citizen Appointment|Hospital Management|Nurse Workstation|Policy Controls|Submit/);
  assert.doesNotMatch(js, /Accept<\/button>|Start<\/button>|Complete<\/button>|view only|hospital dispatch required/);
});
