const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const ROOT = path.resolve(__dirname, "..");

function read(file) {
  return fs.readFileSync(path.join(ROOT, file), "utf8");
}

test("role pages keep explicit page guards", () => {
  const guards = {
    "citizen.html": "citizen",
    "mobile-preview.html": "citizen",
    "institution.html": "institution",
    "insurance.html": "insurance",
    "county.html": "county",
    "index.html": "commission",
    "health-dashboard.html": "commission",
    "platform.html": "commission",
    "workbench.html": "commission",
    "quality-safety.html": "commission"
  };
  Object.entries(guards).forEach(([file, role]) => {
    assert.match(read(file), new RegExp(`requireRole\\(\\[\\"${role}\\"\\]\\)`), `${file} 缺少 ${role} 页面守卫`);
  });
});

test("citizen pages do not expose cross-role module links or management collections", () => {
  const citizenHtml = `${read("citizen.html")}\n${read("mobile-preview.html")}`;
  ["institution.html", "insurance.html", "county.html", "index.html", "platform.html", "workbench.html", "quality-safety.html", "health-dashboard.html"].forEach((target) => {
    assert.doesNotMatch(citizenHtml, new RegExp(`href=[\\"']\\./${target}`), `居民页面不应链接到 ${target}`);
  });

  const citizenAssets = `${citizenHtml}\n${read("citizen.js")}`;
  ["authUsers", "securityEvents", "applicationCatalog", "institutionCreditEvaluations", "securityAcceptanceLedger"].forEach((key) => {
    assert.doesNotMatch(citizenAssets, new RegExp(`\\b${key}\\b`), `居民端资产不应依赖管理集合 ${key}`);
  });
});

test("application pages avoid placeholder navigation", () => {
  const pages = ["about.html", "referral-teleconsultation-about.html", "citizen.html", "mobile-preview.html", "institution.html", "insurance.html", "county.html", "index.html", "platform.html", "workbench.html", "quality-safety.html", "health-dashboard.html"];
  pages.forEach((file) => assert.doesNotMatch(read(file), /href=["']#["']/, `${file} 存在空链接占位`));
});

test("about page documents runnable platform capabilities", () => {
  const about = read("about.html");
  const referralAbout = read("referral-teleconsultation-about.html");
  const auth = read("auth.js");
  assert.match(about, /data-about-section="runtime-capabilities"/);
  assert.match(about, /data-about-section="role-portals"/);
  assert.match(about, /data-about-section="referral-policy"/);
  assert.match(about, /data-about-capability="referral-teleconsultation"/);
  assert.match(about, /data-about-capability="service-acceptance"/);
  assert.match(about, /data-about-capability="site-template-readmes"/);
  assert.match(about, /data-about-capability="workflow-tasks"/);
  assert.match(about, /data-about-capability="chronic-care"/);
  assert.match(about, /data-about-capability="county-consortium"/);
  assert.match(about, /\/api\/service-acceptance-summary/);
  assert.match(about, /\/api\/site-template-readmes/);
  assert.match(about, /\/api\/tasks/);
  assert.match(about, /npm run deploy:check/);
  assert.match(read("index.html"), /href="\.\/about\.html"/);
  assert.match(read("platform.html"), /href="\.\/about\.html"/);
  assert.match(read("health-city.html"), /href="\.\/about\.html"/);
  assert.match(read("institution.html"), /href="\.\/referral-teleconsultation-about\.html"/);
  assert.match(read("county.html"), /href="\.\/referral-teleconsultation-about\.html"/);
  assert.match(auth, /\["about\.html", "关于"\]/);
  assert.match(auth, /referral-teleconsultation-about\.html/);
  assert.match(referralAbout, /data-referral-about-section="policy-basis"/);
  assert.match(referralAbout, /data-referral-policy="graded-diagnosis"/);
  assert.match(referralAbout, /data-referral-about-section="joint-signoff"/);
  assert.match(referralAbout, /data-referral-signoff="referral-center"/);
  assert.match(referralAbout, /data-referral-signoff="receiving-hospital"/);
  assert.match(referralAbout, /data-referral-signoff="hospital-it"/);
  assert.match(referralAbout, /data-referral-signoff="county-performance"/);
  assert.match(referralAbout, /Developer: Dr\.Xu/);
  assert.match(referralAbout, /referral-feedback-callback-v1/);
  assert.match(referralAbout, /feedback-callback/);
  assert.match(referralAbout, /schedule-callback/);
  assert.match(referralAbout, /report-callback/);
  assert.match(referralAbout, /signoff-summary/);
  assert.match(referralAbout, /npm\.cmd run referral:readiness/);
  assert.doesNotMatch(referralAbout, /requireRole/);
  assert.match(auth, /pageName === "about\.html"/);
  assert.doesNotMatch(about, /requireRole/);
});

test("static snapshot keeps completed P2 governance collections", () => {
  const data = JSON.parse(read("data/db.json"));
  assert.equal(data.creditEvaluationRules.version, "credit-rules-2026.1");
  assert.equal(Array.isArray(data.researchDatasets), true);
  assert.equal(data.researchDatasets.some((item) => item.id === "rd-hypertension-001"), true);
  assert.equal(data.researchDatasets.every((item) => item.ethicsStatus && item.deidentificationStatus && item.sandbox && Array.isArray(item.sourceCollections)), true);
  assert.equal(data.dataAccessLogs.some((item) => /research/i.test(`${item.scope || ""} ${item.purpose || ""}`)), true);
  assert.equal(Array.isArray(data.diseaseRegistryModels), true);
  assert.equal(data.diseaseRegistryModels.some((item) => item.id === "dm-hypertension-risk-v1"), true);
  assert.equal(Array.isArray(data.drugConsumableSupervisions), true);
  assert.equal(data.drugConsumableSupervisions.some((item) => item.id === "dcs-rational-r1" && item.boundary === "rational-medication"), true);
  assert.equal(data.drugConsumableSupervisions.some((item) => item.id === "dcs-consumable-mr1" && item.boundary === "consumable-clue"), true);
  assert.equal(data.mobileExperienceSettings.weakNetworkMode, "cache-last-state");
  assert.equal(Array.isArray(data.accessibilityChecklist), true);
  assert.equal(data.accessibilityChecklist.some((item) => item.id === "a11y-large-font"), true);
  assert.equal(Array.isArray(data.productionDeploymentPlan), true);
  assert.equal(data.productionDeploymentPlan.some((item) => item.id === "prod-storage-adapter"), true);
  assert.equal(Array.isArray(data.healthDashboardSnapshots), true);
  assert.equal(data.healthDashboardSnapshots.some((item) => item.sourceApplications.length === 7), true);
  assert.equal(Array.isArray(data.countyAcceptanceLedger), true);
  assert.equal(data.countyAcceptanceLedger.some((item) => item.id === "county-accept-report-return"), true);
  assert.equal(data.countyAcceptanceLedger.some((item) => item.metricKey === "criticalAlert"), true);
  assert.equal(Array.isArray(data.platformInterfaces), true);
  assert.equal(data.platformInterfaces.filter((item) => item.priority === "P0").every((item) => item.owner && item.status && item.next), true);
  assert.equal(data.platformInterfaces.filter((item) => item.priority === "P0").every((item) => item.status === "演示对接完成"), true);
  assert.equal(data.platformInterfaces.some((item) => item.id === "if-medical" && /HIS\/EMR\/LIS\/PACS/.test(item.existing)), true);
  assert.equal(data.platformCapabilities.some((item) => item.id === "cap-data-platform" && item.status === "演示底座闭环"), true);
  assert.equal(data.platformCapabilities.some((item) => item.id === "cap-evaluation" && item.status === "测评证据已建档"), true);
  assert.equal(data.platformCapabilities.some((item) => item.id === "cap-security" && item.status === "安全证据已建档"), true);
  assert.equal(data.applicationCatalog.some((item) => item.id === "app-institution" && item.status === "演示对接完成"), true);
  assert.equal(data.securityAcceptanceLedger.every((item) => item.id && item.category && item.owner && item.status && item.next), true);
  assert.equal(data.securityAcceptanceLedger.every((item) => /建档/.test(item.status)), true);
  assert.equal(data.platformRoadmap.filter((item) => item.priority === "P2").every((item) => item.status === "已完成"), true);
});

test("health dashboard exposes the aggregate application entry and API contract", () => {
  const html = read("health-dashboard.html");
  const js = read("health-dashboard.js");
  const server = read("server.js");
  const release = read("scripts/release-report.js");
  const deploy = read("scripts/deploy-check.js");

  assert.match(html, /卫生健康综合驾驶舱/);
  assert.match(html, /dashboard-applications/);
  assert.match(html, /dashboard-templates/);
  assert.match(html, /dashboard-actions/);
  assert.match(html, /dashboard-interfaces/);
  assert.match(html, /dashboard-evidence/);
  assert.match(html, /dashboard-dependencies/);
  assert.match(js, /\/api\/health-dashboard\/summary/);
  assert.match(js, /functionalBoundary/);
  assert.match(js, /renderTemplates/);
  assert.match(js, /source application/);
  assert.match(server, /\/api\/health-dashboard\/summary/);
  assert.match(server, /buildHealthDashboardSummary/);
  assert.match(release, /health-dashboard-summary/);
  assert.match(deploy, /snapshot:healthDashboard/);
});

test("static snapshot keeps acceptance evidence clean and actionable", () => {
  const raw = read("data/db.json");
  const data = JSON.parse(raw);
  assert.doesNotMatch(raw, /编码损坏，待核验/);
  assert.doesNotMatch(raw, /\?\?\?/);
  assert.doesNotMatch(raw, /�/);
  const interoperability = data.platformEvidence.find((item) => item.id === "ev-interoperability");
  assert.equal(interoperability.status, "已建档");
  assert.equal(interoperability.records.length >= 2, true);
  const security = data.platformEvidence.find((item) => item.id === "ev-security");
  assert.equal(security.status, "已建档");
  assert.equal(security.records.length >= 3, true);
  const launch = data.platformEvidence.find((item) => item.id === "ev-launch");
  assert.equal(launch.status, "演示验收建档");
  assert.equal(launch.records.length >= 3, true);
  assert.equal(interoperability.records.every((item) => item.owner && item.testRecord && item.status), true);
  assert.equal(security.records.every((item) => item.owner && item.testRecord && item.status), true);
  assert.equal(launch.records.every((item) => item.owner && item.testRecord && item.status), true);
  assert.equal(interoperability.records.some((item) => item.link === "/api/system/readiness"), true);
});

test("chronic disease policy module exposes 2025 service capacity workflow", () => {
  const data = JSON.parse(read("data/db.json"));
  const html = read("index.html");
  const app = read("app.js");
  const server = read("server.js");
  ["chronicServiceRoles", "chronicCapabilityConditions", "chronicServicePathways", "chronicComorbidityPlans", "chronicTcmServices", "chronicSelfManagement", "chronicMedicationSupport", "chronicQualityMetrics", "chronicAcceptanceLedger"].forEach((key) => {
    assert.equal(Array.isArray(data[key]), true, `${key} should be seeded`);
    assert.equal(data[key].length > 0, true, `${key} should not be empty`);
  });
  assert.equal(data.chronicAcceptanceLedger.some((item) => item.id === "chronic-accept-quality"), true);
  assert.equal(data.chronicAcceptanceLedger.some((item) => item.metricKey === "selfManagement"), true);
  ["chronic-service-roles", "chronic-capability-conditions", "chronic-service-pathways", "chronic-comorbidity-table", "chronic-tcm-services", "chronic-self-management", "chronic-medication-support", "chronic-quality-metrics"].forEach((id) => {
    assert.match(html, new RegExp(id), `${id} panel should be present`);
  });
  assert.match(html, /chronic-risk-summary/);
  assert.match(html, /chronic-risk-stratification/);
  assert.match(app, /renderChronicPolicyServices/);
  assert.match(app, /applyChronicWorkflowAction/);
  assert.match(app, /renderChronicRiskStratification/);
  assert.match(app, /buildChronicRiskStratification/);
  assert.match(app, /chronicComorbidityPlans/);
  assert.match(app, /chronicMedicationSupport/);
  assert.match(server, /chronic-comorbidity-plans/);
  assert.match(server, /\/api\/chronic\/acceptance-ledger/);
  assert.match(server, /\/api\/chronic\/risk-stratification/);
  assert.match(server, /buildChronicRiskStratification/);
  assert.match(server, /chronicMedicationSupport/);
  assert.match(server, /buildChronicServiceSummary/);
  assert.match(server, /buildCountyServiceSummary/);
  assert.match(server, /DEMO_TODAY/);
  assert.match(server, /2026-06-22/);
  assert.match(server, /changed && !shouldUseSqlite\(\)/);
  assert.match(server, /多病共管/);
  assert.match(server, /基层慢病健康管理中心/);
});

test("insurance portal exposes actionable drug consumable supervision workflow", () => {
  const html = read("insurance.html");
  const js = read("insurance.js");
  const server = read("server.js");
  assert.match(html, /drug-consumable-panel/);
  assert.match(js, /renderDrugConsumableSupervision/);
  assert.match(js, /postDrugConsumableAction/);
  assert.match(js, /data-drug-action/);
  assert.match(server, /buildDrugConsumableSupervision/);
  assert.match(server, /\/api\/drug-consumable-supervision/);
  assert.match(server, /drug-consumable-review/);
  assert.match(server, /drug-consumable-remediation/);
  assert.match(server, /drug-consumable-insurance-sync/);
});

test("deployment baseline documents scripts and environment template", () => {
  const pkg = JSON.parse(read("package.json"));
  const referralAbout = read("referral-teleconsultation-about.html");
  assert.equal(Boolean(pkg.scripts["deploy:check"]), true);
  assert.equal(Boolean(pkg.scripts["env:check"]), true);
  assert.equal(Boolean(pkg.scripts["release:report"]), true);
  assert.equal(Boolean(pkg.scripts["release:manifest"]), true);
  assert.equal(Boolean(pkg.scripts["rollback:snapshot"]), true);
  assert.equal(Boolean(pkg.scripts["storage:inspect"]), true);
  assert.equal(Boolean(pkg.scripts["identity:contract"]), true);
  assert.equal(Boolean(pkg.scripts["audit:retention"]), true);
  assert.equal(Boolean(pkg.scripts["chronic:followup-readiness"]), true);
  assert.equal(Boolean(pkg.scripts["data-quality:report"]), true);
  assert.equal(Boolean(pkg.scripts["quality-safety:report"]), true);
  assert.equal(Boolean(pkg.scripts["drug-consumable:readiness"]), true);
  assert.equal(Boolean(pkg.scripts["environment:matrix"]), true);
  assert.equal(Boolean(pkg.scripts["hospital-operations:readiness"]), true);
  assert.equal(Boolean(pkg.scripts["integration:readiness"]), true);
  assert.equal(Boolean(pkg.scripts["interface:mapping"]), true);
  assert.equal(Boolean(pkg.scripts["regional-data-sharing:report"]), true);
  assert.equal(Boolean(pkg.scripts["research:sandbox"]), true);
  assert.equal(Boolean(pkg.scripts["monitoring:readiness"]), true);
  assert.equal(Boolean(pkg.scripts["referral:readiness"]), true);
  assert.equal(Boolean(pkg.scripts["operations:readiness"]), true);
  assert.equal(Boolean(pkg.scripts["process:audit"]), true);
  assert.equal(Boolean(pkg.scripts["site:pack"]), true);
  assert.equal(Boolean(pkg.scripts["production-db:readiness"]), true);
  assert.equal(Boolean(pkg.scripts["evaluation:evidence"]), true);
  assert.match(read(".env.example"), /SESSION_SECRETS=/);
  assert.match(read(".env.example"), /INTEGRATION_GATEWAY_SECRET=/);
  assert.match(read(".env.example"), /CUTOVER_SITE_INTERFACE_SIGNOFF/);
  assert.match(read(".env.example"), /CUTOVER_DR_REHEARSAL_SIGNOFF/);
  assert.match(read(".env.example"), /OIDC_ISSUER_URL=/);
  assert.match(read(".env.example"), /AUDIT_EXPORT_PATH=/);
  assert.match(read("README.md"), /\/api\/health/);
  assert.match(read("README.md"), /deploy:check/);
  assert.match(read("README.md"), /release:report/);
  assert.match(read("README.md"), /release:manifest/);
  assert.match(read("scripts/release-report.js"), /test:coverage/);
  assert.match(read("scripts/release-report.js"), /test:e2e/);
  assert.match(read("scripts/release-report.js"), /Production cutover checklist/);
  assert.match(read("README.md"), /production-cutover-checklist\.md/);
  assert.match(read("README.md"), /storage-model-inspection\.md/);
  assert.match(read("README.md"), /identity-contract\.md/);
  assert.match(read("README.md"), /audit-retention-report\.md/);
  assert.match(read("docs/chronic-followup-readiness.md"), /chronic-followup-readiness-report\.md/);
  assert.match(read("docs/chronic-followup-readiness.md"), /\/api\/chronic\/followup-feedback/);
  assert.match(read("README.md"), /data-quality-report\.md/);
  assert.match(read("README.md"), /quality-safety-report\.md/);
  assert.match(read("README.md"), /drug-consumable-readiness-report\.md/);
  assert.match(read("README.md"), /environment-matrix-report\.md/);
  assert.match(read("README.md"), /integration-readiness-report\.md/);
  assert.match(read("README.md"), /interface-mapping-report\.md/);
  assert.match(read("scripts/release-report.js"), /regional-data-sharing-report\.md/);
  assert.match(read("README.md"), /research-sandbox-readiness-report\.md/);
  assert.match(read("README.md"), /monitoring-readiness-report\.md/);
  assert.match(read("README.md"), /operations-readiness-report\.md/);
  assert.match(read("README.md"), /hospital-operations-readiness-report\.md/);
  assert.match(read("README.md"), /process-audit-report\.md/);
  assert.match(read("README.md"), /service-acceptance-summary\.md/);
  assert.match(read("README.md"), /\/api\/service-acceptance-summary/);
  assert.match(read("README.md"), /site-readiness-pack\.md/);
  assert.match(read("README.md"), /release\/templates\/\*\/README\.md/);
  assert.match(read("README.md"), /\/api\/site-template-readmes/);
  assert.match(read("README.md"), /production-db-readiness-report\.md/);
  assert.match(read("README.md"), /evaluation-evidence-report\.md/);
  assert.match(read("README.md"), /release-artifact-manifest\.md/);
  assert.match(read("DEPLOYMENT.md"), /storage-model-inspection\.md/);
  assert.match(read("DEPLOYMENT.md"), /identity-contract\.md/);
  assert.match(read("DEPLOYMENT.md"), /audit-retention-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /data-quality-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /quality-safety-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /drug-consumable-readiness-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /environment-matrix-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /integration-readiness-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /interface-mapping-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /research-sandbox-readiness-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /monitoring-readiness-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /operations-readiness-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /hospital-operations-readiness-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /process-audit-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /site-readiness-pack\.md/);
  assert.match(read("DEPLOYMENT.md"), /release\/templates\/\*\/README\.md/);
  assert.match(read("DEPLOYMENT.md"), /\/api\/site-template-readmes/);
  assert.match(read("DEPLOYMENT.md"), /service-acceptance-summary\.md/);
  assert.match(read("DEPLOYMENT.md"), /\/api\/service-acceptance-summary/);
  assert.match(read("DEPLOYMENT.md"), /production-db-readiness-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /evaluation-evidence-report\.md/);
  assert.match(read("DEPLOYMENT.md"), /release-artifact-manifest\.md/);
  assert.match(read("scripts/deploy-check.js"), /test:coverage/);
  assert.match(read("scripts/deploy-check.js"), /test:e2e/);
  assert.match(read("scripts/deploy-check.js"), /audit/);
  assert.match(read("scripts/deploy-check.js"), /identity:contract/);
  assert.match(read("scripts/deploy-check.js"), /audit:retention/);
  assert.match(read("scripts/deploy-check.js"), /chronic:followup-readiness/);
  assert.match(read("scripts/deploy-check.js"), /chronicFollowupStatusPolicy/);
  assert.match(read("scripts/deploy-check.js"), /data-quality:report/);
  assert.match(read("scripts/deploy-check.js"), /quality-safety:report/);
  assert.match(read("scripts/deploy-check.js"), /drug-consumable:readiness/);
  assert.match(read("scripts/deploy-check.js"), /environment:matrix/);
  assert.match(read("scripts/deploy-check.js"), /integration:readiness/);
  assert.match(read("scripts/deploy-check.js"), /interface:mapping/);
  assert.match(read("scripts/deploy-check.js"), /regional-data-sharing:report/);
  assert.match(read("scripts/deploy-check.js"), /monitoring:readiness/);
  assert.match(read("scripts/deploy-check.js"), /referral:readiness/);
  assert.match(read("scripts/deploy-check.js"), /operations:readiness/);
  assert.match(read("scripts/deploy-check.js"), /hospital-operations:readiness/);
  assert.match(read("scripts/deploy-check.js"), /process:audit/);
  assert.match(read("scripts/deploy-check.js"), /site:pack/);
  assert.match(read("scripts/deploy-check.js"), /release:manifest/);
  assert.match(read("scripts/deploy-check.js"), /production-db:readiness/);
  assert.match(read("scripts/deploy-check.js"), /evaluation:evidence/);
  assert.match(read("scripts/deploy-check.js"), /process\.platform === "win32" \? "npm\.cmd" : "npm"/);
  assert.match(read(".github/workflows/ci.yml"), /npm run deploy:check/);
  assert.match(read(".github/workflows/ci.yml"), /npm run storage:inspect/);
  assert.match(read(".github/workflows/ci.yml"), /npm run identity:contract/);
  assert.match(read(".github/workflows/ci.yml"), /npm run audit:retention/);
  assert.match(read(".github/workflows/ci.yml"), /npm run chronic:followup-readiness/);
  assert.match(read(".github/workflows/ci.yml"), /npm run data-quality:report/);
  assert.match(read(".github/workflows/ci.yml"), /npm run quality-safety:report/);
  assert.match(read(".github/workflows/ci.yml"), /npm run drug-consumable:readiness/);
  assert.match(read(".github/workflows/ci.yml"), /npm run integration:readiness/);
  assert.match(read(".github/workflows/ci.yml"), /npm run interface:mapping/);
  assert.match(read(".github/workflows/ci.yml"), /npm run regional-data-sharing:report/);
  assert.match(read(".github/workflows/ci.yml"), /npm run monitoring:readiness/);
  assert.match(read(".github/workflows/ci.yml"), /npm run referral:readiness/);
  assert.match(read("institution.html"), /teleconsultation-form/);
  assert.match(read("institution.html"), /data-referral-layout="institution-flow"/);
  assert.match(read("institution.js"), /teleconsultation-action-form/);
  assert.match(read("institution.js"), /status-ribbon/);
  assert.match(read("institution.js"), /保存反馈/);
  assert.match(read("institution.js"), /data-teleconsultation-ack/);
  assert.match(read("institution.html"), /teleconsultation-loop/);
  assert.match(read("county.html"), /data-referral-layout="county-command"/);
  assert.match(read("county.html"), /county-teleconsultation-status-filter/);
  assert.match(read("county.html"), /county-teleconsultation-priority-filter/);
  assert.match(read("county.html"), /county-teleconsultation-performance/);
  assert.match(read("county.html"), /county-teleconsultation-risk-board/);
  assert.match(read("county.html"), /county-teleconsultation-signoff/);
  assert.match(read("county.js"), /averagePerformance/);
  assert.match(read("county.js"), /SLA risks/);
  assert.equal((read("county.js").match(/function renderCountyTeleconsultationLoop/g) || []).length, 1);
  assert.match(read("county.js"), /buildReferralTeleconsultationEscalations/);
  assert.match(read("county.js"), /renderCountyTeleconsultationRiskBoard/);
  assert.match(read("county.js"), /buildCountyTeleconsultationSignoffRows/);
  assert.match(read("county.js"), /data-referral-signoff-status/);
  assert.match(read("county.js"), /data-referral-signoff-submit/);
  assert.match(read("county.js"), /archiveReferralSignoff/);
  assert.match(read("county.js"), /data-referral-escalation/);
  assert.match(read("county.js"), /data-county-sla-ack/);
  assert.match(read("county.js"), /label\.includes\("关闭"\)/);
  assert.match(read("county.js"), /督办/);
  assert.match(read("county.js"), /runReferralEscalation/);
  assert.match(read("county.js"), /hasReferralEscalationReminder/);
  assert.match(read("server.js"), /buildReferralTeleconsultationEscalations/);
  assert.match(read("server.js"), /referral-teleconsultations\/escalations\/run/);
  assert.match(read("server.js"), /referral-teleconsultations\/joint-test-pack/);
  assert.match(read("server.js"), /referral-teleconsultations\/signoff-summary/);
  assert.match(read("server.js"), /signoff-summary\/:role\/evidence/);
  assert.match(read("server.js"), /upsertReferralTeleconsultationSignoff/);
  assert.match(read("server.js"), /canSubmitReferralSignoff/);
  assert.match(read("server.js"), /buildReferralTeleconsultationSignoffSummary/);
  assert.match(read("server.js"), /mergeByKeyWithDefaultFields\(seedReferralTeleconsultations\(\), data\.referralTeleconsultations, "id"\)/);
  assert.match(read("server.js"), /function mergeByKeyWithDefaultFields/);
  assert.match(read("server.js"), /function mergeDefaultFields/);
  assert.match(read("server.js"), /referral-teleconsultations\/performance-policy/);
  assert.match(read("server.js"), /escalations\/ack/);
  assert.match(read("server.js"), /createReferralTeleconsultationEscalationMessage/);
  assert.match(read("server.js"), /highRisk/);
  assert.match(read("server.js"), /schedule-callback/);
  assert.match(read("server.js"), /feedback-callback/);
  assert.match(read("server.js"), /appendReferralTeleconsultationNotifications/);
  assert.match(read("README.md"), /referral-teleconsultations\/:id\/report-callback/);
  assert.match(read("README.md"), /referral-feedback-callback-v1/);
  assert.match(read("README.md"), /referral-schedule-callback-v1/);
  assert.match(read("README.md"), /referral-teleconsultations\/signoff-summary/);
  assert.match(read("README.md"), /taskMessages/);
  assert.match(read("DEPLOYMENT.md"), /x-integration-signature/);
  assert.match(read("DEPLOYMENT.md"), /feedback-callback/);
  assert.match(read("DEPLOYMENT.md"), /referral-report-callback-v1/);
  assert.match(read("DEPLOYMENT.md"), /referral-teleconsultations\/signoff-summary/);
  assert.match(read("DEPLOYMENT.md"), /institution\/resident `taskMessages`/);
  assert.match(read("county.html"), /county-teleconsultation-loop/);
  assert.match(read("insurance.html"), /referral-performance-policy/);
  assert.match(read("insurance.html"), /data-referral-layout="insurance-policy"/);
  assert.match(read("insurance.js"), /renderReferralPerformancePolicy/);
  assert.match(referralAbout, /data-referral-about-section="participant-progress"/);
  assert.match(referralAbout, /data-referral-role-progress="county-office"/);
  assert.match(read("portal.css"), /grid-template-columns: repeat\(auto-fit, minmax\(220px, 1fr\)\)/);
  assert.match(read("portal.css"), /\.table-wrap table/);
  assert.match(read(".github/workflows/ci.yml"), /npm run operations:readiness/);
  assert.match(read(".github/workflows/ci.yml"), /npm run site:pack/);
  assert.match(read(".github/workflows/ci.yml"), /npm run production-db:readiness/);
  assert.match(read(".github/workflows/ci.yml"), /npm run evaluation:evidence/);
  assert.match(read(".github/workflows/ci.yml"), /npm run release:manifest/);
  assert.match(read(".github/workflows/ci.yml"), /npm run release:report/);
  assert.match(read(".github/workflows/ci.yml"), /actions\/upload-artifact@v4/);
  assert.match(read(".github/workflows/ci.yml"), /release-readiness-report/);
  assert.match(read(".github/workflows/ci.yml"), /npm audit --omit=dev/);
});

test("regional data sharing application has runnable entry, API and evidence script", () => {
  const html = read("regional-data-sharing.html");
  const client = read("regional-data-sharing.js");
  const server = read("server.js");
  const script = read("scripts/regional-data-sharing.js");
  const data = JSON.parse(read("data/db.json"));

  assert.match(html, /区域诊疗数据共享平台/);
  assert.match(html, /regional-data-sharing\.js/);
  assert.match(client, /\/api\/regional-data-sharing/);
  assert.match(client, /调阅留痕/);
  assert.match(server, /seedRegionalDataSharingScope/);
  assert.match(server, /createRegionalSharingAccessReview/);
  assert.match(server, /\/api\/regional-data-sharing\/access-reviews/);
  assert.match(script, /buildRegionalDataSharingReport/);
  assert.equal(data.regionalDataSharingScope.reusedCollections.includes("residents"), true);
  assert.equal(data.regionalDataSharingScope.exclusions.length >= 3, true);
  assert.equal(data.regionalSharingPackages.length >= 3, true);
  assert.equal(data.regionalSharingPackages.every((item) => ["ready", "pending_review", "blocked", "archived"].includes(item.status)), true);
});

test("platform and workbench expose P2 governance and runtime panels", () => {
  const platformHtml = read("platform.html");
  const platformJs = read("platform.js");
  const workbenchHtml = read("workbench.html");
  const workbenchJs = read("workbench.js");
  const operationsHtml = read("operations.html");
  const operationsJs = read("operations.js");
  assert.match(platformHtml, /research-governance/);
  assert.match(platformJs, /runResearchDatasetAction/);
  assert.match(platformJs, /sandbox-access/);
  assert.match(platformJs, /outcome-return/);
  assert.match(platformHtml, /mobile-accessibility-governance/);
  assert.match(platformHtml, /production-deployment-plan/);
  assert.match(platformJs, /renderResearchGovernance/);
  assert.match(platformJs, /renderMobileAccessibilityGovernance/);
  assert.match(platformJs, /renderProductionDeploymentPlan/);
  assert.match(platformJs, /evr-interoperability-contracts/);
  assert.match(platformJs, /integration-readiness-report\.md/);
  assert.match(platformJs, /audit-retention-report\.md/);
  assert.match(platformJs, /HIS\/EMR\/LIS\/PACS 契约和网关模拟接入/);
  assert.doesNotMatch(platformJs, /domain: "统一认证"[^\n]*status: "开发中"/);
  assert.doesNotMatch(platformJs, /domain: "医疗机构业务系统"[^\n]*status: "待接口"/);
  assert.match(workbenchHtml, /system-readiness/);
  assert.match(workbenchHtml, /release-evidence-gates/);
  assert.match(workbenchHtml, /acceptance-ledgers/);
  assert.match(workbenchHtml, /site-readiness-pack/);
  assert.match(workbenchJs, /loadOperationalMetrics/);
  assert.match(workbenchJs, /loadSystemReadiness/);
  assert.match(workbenchJs, /loadAcceptanceLedgers/);
  assert.match(workbenchJs, /loadServiceAcceptanceSummary/);
  assert.match(workbenchJs, /data-service-open-action/);
  assert.match(workbenchJs, /loadSiteReadinessPack/);
  assert.match(workbenchJs, /loadSiteTemplateReadmes/);
  assert.match(workbenchJs, /loadReleaseReport/);
  assert.match(workbenchJs, /loadProductionCutoverChecklist/);
  assert.match(workbenchJs, /loadReleaseArtifactManifest/);
  assert.match(workbenchJs, /loadUnifiedTaskReport/);
  assert.match(workbenchJs, /data-unified-task/);
  assert.match(workbenchJs, /renderReleaseEvidenceGates/);
  assert.match(workbenchJs, /data-quality:report/);
  assert.match(workbenchJs, /operations:readiness/);
  assert.match(workbenchJs, /process:audit/);
  assert.match(workbenchJs, /service:acceptance/);
  assert.match(workbenchJs, /site:pack/);
  assert.match(workbenchJs, /release:manifest/);
  assert.match(workbenchJs, /production:cutover/);
  assert.match(workbenchJs, /evaluation:evidence/);
  assert.match(read("server.js"), /release-artifact-manifest/);
  assert.match(workbenchJs, /\/api\/metrics/);
  assert.match(workbenchJs, /\/api\/system\/readiness/);
  assert.match(workbenchJs, /\/api\/process-audit/);
  assert.match(workbenchJs, /\/api\/service-acceptance-summary/);
  assert.match(workbenchJs, /\/api\/site-readiness-pack/);
  assert.match(workbenchJs, /\/api\/site-template-readmes/);
  assert.match(workbenchJs, /\/api\/release-report/);
  assert.match(workbenchJs, /\/api\/production-cutover-checklist/);
  assert.match(workbenchJs, /\/api\/release-artifact-manifest/);
  assert.match(workbenchJs, /\/api\/tasks/);
  assert.match(workbenchJs, /\/api\/chronic\/acceptance-ledger/);
  assert.match(workbenchJs, /\/api\/county\/acceptance-ledger/);
  assert.match(read("server.js"), /\/api\/process-audit/);
  assert.match(read("server.js"), /\/api\/service-acceptance-summary/);
  assert.match(read("server.js"), /\/api\/site-readiness-pack/);
  assert.match(read("server.js"), /SERVICE_DOMAIN_BY_COLLECTION/);
  assert.match(read("server.js"), /priorityLevel/);
  assert.match(read("server.js"), /\/api\/site-template-readmes/);
  assert.match(read("server.js"), /\/api\/release-report/);
  assert.match(read("server.js"), /\/api\/production-cutover-checklist/);
  assert.match(read("server.js"), /\/api\/release-artifact-manifest/);
  assert.match(operationsHtml, /operations-snapshots/);
  assert.match(operationsHtml, /dispatch-form/);
  assert.match(operationsHtml, /reconciliation-reviews/);
  assert.match(operationsJs, /fetchOperationsDashboard/);
  assert.match(operationsJs, /\/operations\/dashboard/);
  assert.match(operationsJs, /\/operations\/dispatch/);
  assert.match(operationsJs, /\/operations\/reconciliation/);
  assert.match(read("server.js"), /\/api\/operations\/dashboard/);
  assert.match(read("server.js"), /operations-dispatch/);
  assert.match(read("server.js"), /statistics-reconciliation-review/);
});

test("quality safety supervision app exposes runnable portal, API and release evidence", () => {
  const data = JSON.parse(read("data/db.json"));
  const html = read("quality-safety.html");
  const js = read("quality-safety.js");
  const server = read("server.js");
  ["qualitySafetyEvents", "criticalValueAlerts", "clinicalPathwayCases", "medicalRecordQualityReviews", "mutualRecognitionQualityReviews", "qualityRectificationOrders"].forEach((key) => {
    assert.equal(Array.isArray(data[key]), true, `${key} should be seeded`);
    assert.equal(data[key].length > 0, true, `${key} should not be empty`);
  });
  ["diagnosticReports", "countyMutualRecognitionRecords", "dataQualityIssues", "institutionCreditEvaluations", "securityEvents", "hospitalInteroperabilityFunctions"].forEach((key) => {
    assert.match(read("scripts/quality-safety-report.js"), new RegExp(key));
  });
  assert.match(html, /quality-safety-metrics/);
  assert.match(html, /quality-safety-issues/);
  assert.match(html, /quality-safety-rectifications/);
  assert.match(js, /loadQualitySafety/);
  assert.match(js, /dispatchIssue/);
  assert.match(js, /submitFeedback/);
  assert.match(js, /reviewOrder/);
  assert.match(server, /\/api\/quality-safety\/dashboard/);
  assert.match(server, /\/api\/quality-safety\/issues\/:id\/dispatch/);
  assert.match(server, /\/api\/quality-safety\/rectifications\/:id\/feedback/);
  assert.match(server, /\/api\/quality-safety\/rectifications\/:id\/review/);
  assert.match(read("scripts/release-report.js"), /qualitySafety:report/);
  assert.match(read("platform.html"), /quality-safety\.html/);
  assert.match(read("workbench.html"), /quality-safety\.html/);
  assert.match(read("auth.js"), /quality-safety\.html/);
  assert.match(read("server.js"), /\/api\/chronic\/followup-summary/);
  assert.match(read("server.js"), /\/api\/chronic\/followup-feedback/);
  assert.match(read("server.js"), /\/api\/chronic\/followup-dispatch/);
  assert.match(read("institution.html"), /chronic-followup-workbench/);
  assert.match(read("institution.js"), /dispatchChronicFollowup/);
  assert.match(read("citizen.html"), /followup-feedback-form/);
  assert.match(read("citizen.js"), /bindFollowupFeedback/);
});

test("system structure documentation reflects completed local governance loops", () => {
  const systemDoc = read("docs/慢病平台系统结构图与优化建议.md");
  assert.match(systemDoc, /后续优先级边界/);
  assert.match(systemDoc, /本地已完成签名会话、接口级权限/);
  assert.match(systemDoc, /已完成 HIS\/EMR\/LIS\/PACS\/医保\/证照\/统计契约/);
  assert.match(systemDoc, /生产切换证据深化/);
});

test("citizen portal exposes P1 record details trends and source labels", () => {
  const citizenHtml = read("citizen.html");
  const citizenJs = read("citizen.js");
  const citizenCss = read("citizen.css");
  assert.match(citizenHtml, /citizen-trend-grid/);
  assert.match(citizenJs, /renderHealthTrends/);
  assert.match(citizenJs, /buildCitizenTrendSeries/);
  assert.match(citizenJs, /renderCitizenTrend/);
  assert.match(citizenJs, /record-detail/);
  assert.match(citizenJs, /renderSourceBadge/);
  assert.match(citizenJs, /classifyDataSource/);
  assert.match(citizenCss, /citizen-trend-card/);
  assert.match(citizenCss, /source-badge/);
  assert.match(citizenCss, /record-detail/);
});

test("citizen portal exposes PWA install and offline shell assets", () => {
  const citizenHtml = read("citizen.html");
  const manifest = JSON.parse(read("manifest.webmanifest"));
  const serviceWorker = read("service-worker.js");
  assert.match(citizenHtml, /rel="manifest"/);
  assert.match(citizenHtml, /serviceWorker\.register\("\.\/service-worker\.js"\)/);
  assert.equal(manifest.start_url, "./citizen.html");
  assert.equal(manifest.display, "standalone");
  assert.equal(manifest.icons.some((item) => item.src === "./pwa-icon.svg"), true);
  assert.match(serviceWorker, /CACHE_NAME/);
  assert.match(serviceWorker, /citizen\.html/);
  assert.match(serviceWorker, /mobile-preview\.html/);
  assert.match(serviceWorker, /data\/db\.json/);
  assert.match(read("package.json"), /node --check service-worker\.js/);
  assert.match(read("README.md"), /manifest\.webmanifest/);
  assert.match(read("README.md"), /service-worker\.js/);
});

test("citizen portal exposes P2 imaging and attachment archive categories", () => {
  const citizenHtml = read("citizen.html");
  const citizenJs = read("citizen.js");
  assert.match(citizenHtml, /value="imaging"/);
  assert.match(citizenHtml, /value="attachments"/);
  assert.match(citizenJs, /key: "imaging"/);
  assert.match(citizenJs, /key: "attachments"/);
  assert.match(citizenJs, /PACS/);
  assert.match(citizenJs, /attachmentType/);
  assert.match(citizenJs, /renderAttachmentMeta/);
  assert.match(read("citizen.css"), /attachment-meta/);
  assert.match(citizenJs, /buildHealthTimeline\(archive, records, labs, medications, allergies, vaccines, admissions, imaging, attachments\)/);
  assert.match(read("README.md"), /影像资料和附件资料/);
  assert.match(read("docs/C端全流程审计与优化清单.md"), /PWA manifest/);
  assert.match(read("docs/C端全流程审计与优化清单.md"), /影像资料、附件资料/);
});
