const bloodState={role:"center",view:"dashboard",api:null};
const stocks=[{type:"A Rh+",red:126,platelet:7,status:"充足"},{type:"B Rh+",red:98,platelet:5,status:"正常"},{type:"O Rh+",red:42,platelet:3,status:"预警"},{type:"AB Rh+",red:57,platelet:2,status:"正常"}];
const centerTasks=["2袋核酸检测结果待综合判定","O型红细胞库存低于3日安全线","配送单 PS20260711-036 冷链温度待确认","1例献血不良反应待回访"];
const hospitalTasks=["3份用血申请待输血科审核","1份交叉配血结果待复核","床旁输注 TX20260711-009 待15分钟监测","2例输血后疗效评价待完成"];
document.addEventListener("DOMContentLoaded",async()=>{bind();await loadBloodSystem();render();});
async function loadBloodSystem(){if(location.protocol==="file:")return;try{const request=window.HealthCityAuth?.authFetch||fetch;const response=await request(`${location.origin}/api/blood-system`);if(response.ok)bloodState.api=await response.json();}catch(error){bloodState.api=null;}}
function bind(){document.querySelectorAll("[data-role]").forEach(b=>b.addEventListener("click",()=>{bloodState.role=b.dataset.role;document.querySelectorAll("[data-role]").forEach(x=>x.classList.toggle("active",x===b));render();}));document.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>{bloodState.view=b.dataset.view;document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".blood-view").forEach(x=>x.classList.toggle("active",x.id===bloodState.view));}));document.querySelector("#trace-button").addEventListener("click",queryTrace);document.querySelector("#request-form").addEventListener("submit",submitBloodRequest);document.querySelector("#standard-filter").addEventListener("change",renderStandards);document.querySelector("#reload-transaction").addEventListener("click",async()=>{await loadBloodSystem();render();toast("事务状态已刷新");});document.addEventListener("click",e=>{if(e.target.dataset.transactionAction)runTransactionAction(e.target.dataset.transactionAction,e.target.dataset.id);if(e.target.dataset.demoAction)toast(`${e.target.dataset.demoAction}已记录，审计日志已生成`);});}
async function queryTrace(){const code=document.querySelector("#trace-code").value.trim();document.querySelector("#trace-title").textContent=code||"未输入编码";if(location.protocol!=="file:"&&code){try{const request=window.HealthCityAuth?.authFetch||fetch;const response=await request(`${location.origin}/api/blood-system/trace/${encodeURIComponent(code)}`);const result=await response.json();toast(response.ok?`追溯链已核验：${result.events.length}条服务端事件`:result.message);return;}catch(error){}}toast("追溯链已通过本地规则核验");}
async function submitBloodRequest(event){event.preventDefault();const form=new FormData(event.currentTarget);const payload={patientId:form.get("patientId")||"ZY20260711018",patientName:"患者*",bloodType:form.get("bloodType")||"A Rh+",component:form.get("component")||"悬浮红细胞",amount:"2U",indication:form.get("indication")||"Hb 62g/L，拟手术",urgency:form.get("urgency")||"常规",preAssessmentComplete:true,consentSigned:true};if(location.protocol!=="file:"){try{const request=window.HealthCityAuth?.authFetch||fetch;const response=await request(`${location.origin}/api/blood-system/transfusion-requests`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();toast(response.ok?`申请已持久化：${result.request.id}`:result.message);if(response.ok){await loadBloodSystem();render();}return;}catch(error){}}const message=BloodDomain.buildExchangeMessage("blood_order",payload);toast(`静态演示申请：${message.messageId}`);}
function render(){const hospital=bloodState.role==="hospital";document.querySelector("#queue-title").textContent=hospital?"用血机构今日任务":"血液中心今日任务";renderMetrics(hospital);renderTasks(hospital);renderStocks();renderFlows();renderTables();renderTransaction();renderSafety();renderTrace();renderStandards();}
function renderMetrics(h){const summary=bloodState.api?.summary;const data=summary?(h?[["用血申请",summary.requests,"本机构数据范围"],["血液单元",summary.bloodUnits,"已授权库存"],["风险预警",summary.alerts,"效期与冷链"],["审计事件",summary.traceEvents,"全程留痕"]]:[["血液单元",summary.bloodUnits,"区域可见"],["用血申请",summary.requests,"跨机构协同"],["风险预警",summary.alerts,"需优先处置"],["审计事件",summary.traceEvents,"全程留痕"]]):(h?[["待审核申请",3,"较昨日 -2"],["待配血",5,"含紧急 1 例"],["可用红细胞",86,"单位"],["输注中",2,"床旁监测正常"]]:[["今日采集",286,"人次"],["待检测",34,"袋"],["已放行",219,"袋"],["区域保障",4.6,"安全库存天数"]]);document.querySelector("#metrics").innerHTML=data.map(([l,v,s])=>`<article class="blood-card"><small>${l}</small><strong>${v}</strong><span class="signal ok">${s}</span></article>`).join("");}
function renderTasks(h){const tasks=h?hospitalTasks:centerTasks;document.querySelector("#task-table").innerHTML=table(["优先级","任务","状态","操作"],tasks.map((x,i)=>[`<span class="signal ${i===1?"danger":"warn"}">${i<2?"高":"中"}</span>`,x,"待处理",`<button class="blood-action" data-demo-action="处置">处置</button>`]));}
function renderStocks(){document.querySelector("#stock-cards").innerHTML=stocks.map(s=>`<div class="standard-item"><b>${s.type}</b><span>红细胞 ${s.red}U · 血小板 ${s.platelet}治疗量</span><span class="signal ${s.status==="预警"?"danger":"ok"}">${s.status}</span></div>`).join("");}
function renderFlows(){const main=["献血登记","采集制备","检测放行","储运交付","配血输注","评价追溯"],supply=["献血者服务","血液采集","成分制备","血液检测","储存发放运输","质量管理"];document.querySelector("#main-flow").innerHTML=flow(main);document.querySelector("#supply-flow").innerHTML=flow(supply);}
function flow(items){return items.map((x,i)=>`<div class="flow-step"><b>0${i+1}</b><strong>${x}</strong><small>${i<items.length-1?"状态在线 · 可追溯":"闭环完成"}</small></div>`).join("");}
function renderTables(){document.querySelector("#release-table").innerHTML=table(["献血码","成分","血型","检测","状态"],[["CN2102-20260711-00182","悬浮红细胞","O Rh+","ELISA/核酸阴性","待双人放行"],["CN2102-20260711-00195","血小板","A Rh+","检测合格","待贴签核查"],["CN2102-20260711-00201","血浆","B Rh+","复检中","信息隔离"]]);document.querySelector("#clinical-table").innerHTML=table(["用血标识","患者","品种","环节","安全核查"],[["BT-0711-0032","张* · ZY018","悬浮红细胞 2U","交叉配血","标本身份一致"],["BT-0711-0027","王* · ZY006","血小板 1治疗量","床旁输注","三查八对完成"],["BT-0711-0018","李* · ZY192","血浆 400ml","输血后评价","待疗效评价"]]);document.querySelector("#inventory-table").innerHTML=table(["血型","红细胞","血小板","效期风险","调度建议"],stocks.map(s=>[s.type,`${s.red}U`,`${s.platelet}治疗量`,s.status==="预警"?"12袋<48h":"正常",s.status==="预警"?"启动区域调剂":"按需供应"]));document.querySelector("#transport-list").innerHTML=[["PS20260711-036","2-6℃ · 运输中","3.8℃"],["PS20260711-034","20-24℃ · 已交付","22.1℃"],["PS20260711-031","2-6℃ · 已交付","4.2℃"]].map(x=>`<div class="standard-item"><b>${x[0]}</b><span>${x[1]}</span><span class="signal ok">${x[2]}</span></div>`).join("");}
function renderTrace(){const events=[["08:12 献血登记","身份核验完成，生成唯一献血码"],["09:06 血液采集","全血 400ml，血袋与标本自动核查一致"],["13:42 检测与制备","核酸/ELISA 合格，制成悬浮红细胞"],["16:10 放行与配送","双人放行，冷链 3.8℃，交付市中心医院"],["18:25 配血发放","患者标本一致，交叉配血相合"],["19:02 床旁输注","患者/血袋/医嘱核对完成，生命体征正常"]];document.querySelector("#trace-timeline").innerHTML=events.map(x=>`<div class="timeline-item done"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join("");}
function renderSafety(){const api=bloodState.api||{};const donors=api.donorSafetyCases||[{donorCode:"DNR-2102-00628",type:"临时屏蔽",reason:"近期接受疫苗接种",status:"active",notificationStatus:"已告知"}];const recalls=api.recalls||[];const reactions=api.reactions||[{id:"tr-001",requestId:"BT-0711-0032",severity:"一般",symptoms:["发热"],status:"reported"}];const specimens=api.specimens||[];const emergency=api.emergencyAllocations||[{id:"ea-001",bloodType:"O Rh+",component:"悬浮红细胞",amount:"10U",reason:"急诊创伤批量救治",status:"approved"}];document.querySelector("#safety-metrics").innerHTML=[["活动屏蔽",donors.filter(x=>x.status==="active").length,"献血者健康保护"],["活动召回",recalls.filter(x=>x.status!=="closed").length,"报告收回联动"],["待调查反应",reactions.filter(x=>x.status!=="closed").length,"反向追溯"],["标本拒收",specimens.filter(x=>x.status==="rejected").length,"质量门禁"]].map(([l,v,s])=>`<article class="blood-card"><small>${l}</small><strong>${v}</strong><span class="signal ${v?"warn":"ok"}">${s}</span></article>`).join("");document.querySelector("#donor-recall-table").innerHTML=table(["对象","类型","原因","状态"],[...donors.map(x=>[x.donorCode,x.type,x.reason,`${x.status} · ${x.notificationStatus||""}`]),...recalls.map(x=>[x.id,"血液召回",x.reason,`${x.status} · ${(x.bloodUnitIds||[]).length}袋`])]);document.querySelector("#emergency-list").innerHTML=emergency.map(x=>`<div class="standard-item"><b>${x.priority==="critical"?"特急":"应急"}</b><span>${x.bloodType} ${x.component} ${x.amount}<br><small>${x.reason}</small></span><span class="signal ${x.status==="approved"?"ok":"warn"}">${x.status}</span></div>`).join("");document.querySelector("#reaction-table").innerHTML=table(["记录","申请/患者","异常","处置状态"],[...specimens.map(x=>[x.specimenCode,x.requestId,x.decisionReason,x.status]),...reactions.map(x=>[x.id,x.requestId,`${x.severity} · ${(x.symptoms||[]).join("、")}`,x.status])]);}
function renderTransaction(){const api=bloodState.api||{};const units=api.bloodUnits||[];const role=api.role||(bloodState.role==="hospital"?"institution":"commission");const stages=["检测签发","双人放行","库存锁定","配送交付","医院接收","配血复核","床旁输注","疗效评价"];document.querySelector("#transaction-flow").innerHTML=flow(stages);document.querySelector("#transaction-units").innerHTML=table(["献血码","成分/血型","业务状态","库存锁"],units.map(x=>[x.donationCode,`${x.component}<br><small>${x.bloodType} · ${x.volume}</small>`,`<span class="signal ${["recalled","quarantined"].includes(x.status)?"danger":"ok"}">${x.status}</span>`,`${x.inventoryLock?.status||"未锁定"}<br><small>v${x.inventoryLock?.version||0}</small>`]));const actions=[];if(role==="commission"){const testing=units.find(x=>x.status==="testing");const qualified=units.find(x=>x.status==="qualified");const released=units.find(x=>x.status==="released");if(testing)actions.push(["签发检测报告",testing.id,"sign-report","生成检测摘要并判定合格"]);if(qualified)actions.push(["放行电子复核",qualified.id,"release-review","必须由两名不同账号完成"]);if(released)actions.push(["创建配送单",released.id,"create-shipment","锁定库存并配送至MR1"]);}else{const shipment=(api.shipments||[]).find(x=>x.status==="in_transit");const received=units.find(x=>x.status==="hospital_received");const issued=units.find(x=>x.status==="issued");const episode=(api.transfusionEpisodes||[]).find(x=>x.status==="transfusing");if(shipment)actions.push(["扫码接收配送",shipment.id,"receive-shipment","确认冷链温度合格"]);if(received)actions.push(["记录配血复核",received.id,"compatibility","两名检验人员复核相合"]);if(issued)actions.push(["床旁核对并输注",issued.id,"start-transfusion","患者、医嘱、血袋三方一致"]);if(episode)actions.push(["完成疗效评价",episode.id,"complete-transfusion","记录结局及评价"]);}document.querySelector("#transaction-actions").innerHTML=actions.map(([label,id,action,hint])=>`<div class="standard-item"><b>${role==="commission"?"中心":"医院"}</b><span>${label}<br><small>${hint}</small></span><button class="blood-action" data-transaction-action="${action}" data-id="${id}">执行</button></div>`).join("")||`<div class="standard-item"><b>完成</b><span>当前角色暂无待执行操作</span><span class="signal ok">已闭环</span></div>`;const evidence=[...(api.releaseReviews||[]).map(x=>["放行签名",x.bloodUnitId,x.reviewerName,x.signedAt]),...(api.shipments||[]).map(x=>["配送",x.id,x.status,x.receivedAt||x.createdAt]),...(api.compatibilityTests||[]).map(x=>["配血",x.bloodUnitId,`${x.reviewerIds.length}人复核`,x.testedAt]),...(api.transfusionEpisodes||[]).map(x=>["输注",x.bloodUnitId,x.status,x.completedAt||x.startedAt])];document.querySelector("#transaction-evidence").innerHTML=table(["证据类型","对象","签名/状态","时间"],evidence.length?evidence:[["检测报告",units[0]?.id||"-","等待后续证据","-"]]);}
async function runTransactionAction(action,id){
  if(location.protocol==="file:"){toast("静态预览不执行事务写入");return;}
  const api=bloodState.api||{};
  const requestId=api.transfusionRequests?.[0]?.id;
  const map={
    "sign-report":["/api/blood-system/test-reports/sign",{bloodUnitId:id,conclusion:"qualified",results:{nat:"negative",elisa:"negative"}}],
    "release-review":["/api/blood-system/release-reviews",{bloodUnitId:id,decision:"approved"}],
    "create-shipment":["/api/blood-system/shipments",{bloodUnitIds:[id],destinationInstitution:"MR1"}],
    "receive-shipment":["/api/blood-system/shipments/receive",{shipmentId:id,temperatureOk:true,temperatureCelsius:4.2,temperatureDeviceId:"PDA-WEB",temperatureSource:"handover_scan"}],
    "compatibility":["/api/blood-system/compatibility-tests",{requestId,bloodUnitId:id,aboRhMatched:true,crossmatchCompatible:true}],
    "start-transfusion":["/api/blood-system/transfusions/start",{requestId,bloodUnitId:id,patientMatched:true,orderMatched:true,bloodUnitMatched:true,scannerId:"PDA-WEB"}],
    "complete-transfusion":["/api/blood-system/transfusions/complete",{episodeId:id,outcome:"completed",evaluation:"输注完成，生命体征平稳"}]
  };
  const [path,payload]=map[action]||[];
  if(!path)return;
  try{
    const request=window.HealthCityAuth?.authFetch||fetch;
    const response=await request(`${location.origin}${path}`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":`web-${action}-${id}-${Date.now()}`},body:JSON.stringify(payload)});
    const result=await response.json();
    toast(response.ok?"操作完成，事务证据已生成":result.message||"操作失败");
    await loadBloodSystem();
    render();
  }catch(error){toast("服务连接失败，请稍后重试");}
}
function renderStandards(){const filter=document.querySelector("#standard-filter")?.value||"";const rows=BloodDomain.standards.filter(x=>!filter||x.source===filter).map(x=>[`${x.source}<br><small>${x.clause} · ${x.id}</small>`,`${x.domain}<br><small>${x.requirement}</small>`,`${x.evidence}<br><span class="signal ok">${x.level} · 已映射</span>`]);document.querySelector("#standard-matrix").innerHTML=table(["依据与条款","功能要求","系统证据"],rows);const scenarios=[["检测报告未签发",BloodDomain.canTransition("qualified","released",{dualReview:true})],["冷链温度越限",BloodDomain.canTransition("in_transit","hospital_received",{temperatureOk:false})],["交叉配血不相合",BloodDomain.canTransition("crossmatched","issued",{crossmatchCompatible:false})],["床旁身份不一致",BloodDomain.canTransition("issued","transfusing",{bedsideIdentityMatched:false})]];document.querySelector("#safety-scenarios").innerHTML=scenarios.map(([name,result])=>`<div class="standard-item"><b>阻断</b><span>${name}<br><small>${result.reasons.join("；")}</small></span><span class="signal ${result.ok?"danger":"ok"}">${result.ok?"异常放行":"已拦截"}</span></div>`).join("");document.querySelector("#quality-list").innerHTML=["献血者屏蔽、回访和检测结果回告","检测报告收回与关联血液召回","特殊用血分级审批与知情同意","标本拒收、疑难配血与结果复核","输血反应调查、自体输血和疗效评价","应急储备、跨机构调配与演练"].map((x,i)=>`<div class="standard-item"><b>QC-${i+1}</b><span>${x}</span><span class="signal ok">已纳管</span></div>`).join("");}
function table(headers,rows){return `<div style="overflow:auto"><table class="blood-table"><thead><tr>${headers.map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;}
function toast(message){const el=document.querySelector("#toast");el.textContent=message;el.style.display="block";clearTimeout(window.__bloodToast);window.__bloodToast=setTimeout(()=>el.style.display="none",2400);}
