server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /dicom-web/ {
    proxy_pass http://orthanc:8042/dicom-web/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /wado/ {
    proxy_pass http://orthanc:8042/wado/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
